// Generated by npm run sync:aperture-release. Do not edit manually.
export const APERTURE_RELEASE = Object.freeze({
  "schema": "td613.aperture.release/v1",
  "version": "v3.0-alpha",
  "apertureSchema": "td613-aperture/v3.0-alpha",
  "featureVersion": "v3.0-alpha-anti-epistemicide-research-runtime",
  "doctrineKernelSchema": "td613.aperture.doctrine-kernel/v2.9.4",
  "domeBridgeSchema": "td613.aperture.reciprocal-receipt-bridge/v3.0-alpha",
  "domeDiagnosticReceiptSchema": "td613.aperture.diagnostic-receipt/v3.0-alpha",
  "flowCoreContextReceiptSchema": "td613.flowcore.context-receipt/vNext",
  "roundTripReceiptSchema": "td613.aperture.round-trip-receipt/v3.0-alpha",
  "bridgePosture": "reciprocal_receipts_without_reciprocal_authority",
  "domeWorld": {
    "version": "v0.5.0",
    "schema": "td613.dome-world/v0.5.0",
    "exactReceiptSchema": "td613.dome-world.exact-receipt/v0.4.3"
  },
  "observedRegime": "PRCS-A",
  "eorfd": {
    "operationalState": "interface_context",
    "claimAuthority": "design_signal",
    "targetOperationalState": "verified_runtime_installation"
  }
});
