// Generated by npm run sync:aperture-release. Do not edit manually.
export const APERTURE_RELEASE = Object.freeze({
  "schema": "td613.aperture.release/v1",
  "version": "v3.0-alpha",
  "apertureSchema": "td613-aperture/v3.0-alpha",
  "featureVersion": "v3.0-alpha-anti-epistemicide-research-runtime",
  "doctrineKernelSchema": "td613.aperture.doctrine-kernel/v2.9.4",
  "domeBridgeSchema": "td613.aperture.reciprocal-receipt-bridge/v3.0-alpha",
  "phase4BridgeContract": "td613.phase4.reciprocal-bridge/v0.1",
  "phase4ReadinessStatus": "phase-4-active",
  "phase4ProductionStatus": "IMPLEMENTED_PRODUCTION_DEMONSTRATED",
  "domeDiagnosticReceiptSchema": "td613.aperture.diagnostic-receipt/v3.0-alpha",
  "flowCoreContextReceiptSchema": "td613.flowcore.context-receipt/v0.1",
  "legacyFlowCoreContextReceiptSchema": "td613.flowcore.context-receipt/vNext",
  "returnedContextAuditSchema": "td613.aperture.returned-context-audit/v0.1",
  "roundTripReceiptSchema": "td613.aperture.round-trip-receipt/v3.0-alpha",
  "bridgePosture": "reciprocal_receipts_without_reciprocal_authority",
  "phase5RelationRuntime": "td613.phase5.relation-runtime/v0.1",
  "phase5RelationEnvelopeSchema": "td613.relation-envelope/v0.1",
  "phase5RelationConfirmationSchema": "td613.relation-confirmation-receipt/v0.1",
  "phase5RelationAuditSchema": "td613.aperture.relation-audit/v0.1",
  "phase5PhasonEventSchema": "td613.phason.relation-event/v0.1",
  "phase5PhasonChainSchema": "td613.phason.relation-chain/v0.1",
  "phase5ReplaySchema": "td613.relation-replay-receipt/v0.1",
  "phase5Status": "IMPLEMENTED_VALIDATION_GATED",
  "phase5ProductionStatus": "PRODUCTION_GATED",
  "phase5Boundaries": {
    "newServerlessFunction": false,
    "serverPersistence": false,
    "operatorConfirmationRequired": true,
    "automaticAshAction": false,
    "predictionAuthorized": false,
    "openFieldAutoPromotion": false,
    "marrowlineConfirmationAuthority": false
  },
  "domeWorld": {
    "version": "v0.5.0",
    "schema": "td613.dome-world/v0.5.0",
    "exactReceiptSchema": "td613.dome-world.exact-receipt/v0.4.3"
  },
  "observedRegime": "PRCS-A",
  "eorfd": {
    "operationalState": "interface_context",
    "claimAuthority": "design_signal",
    "targetOperationalState": "verified_runtime_installation"
  }
});
