import pathlib,json,hashlib,subprocess,datetime,shutil,base64
ROOT=pathlib.Path('/workspace/scratch/26d2ceda3f9e'); RUN=ROOT/'continuation-a19'; PRIOR=ROOT/'continuation-a18'; CALLER=ROOT/'caller-a19'
def read(p):return json.loads(p.read_bytes())
def h(b):return hashlib.sha256(b).hexdigest()
def write(p,v):
 if p.exists():
  assert read(p)==v;return
 with p.open('x') as f:json.dump(v,f,indent=2,ensure_ascii=False);f.write('\n')
def remote(n):
 v=read(RUN/n);return v['content'].encode() if v['encoding']=='utf-8' else base64.b64decode(v['content'],validate=True)
assert h((RUN/'PLAN_DRAFT.json').read_bytes())=='3629abe9d574a6c87898af1d59ce09b56ba7316766801f8d615a68528bf06391'
assert h((PRIOR/'PLAN.json').read_bytes())=='4d80eefcf56997f8d41856b478e25bebfb78f63a02bc0460cea40c94c09aa0b4'
ledger=read(RUN/'LIVE_LEDGER_PRE_FREEZE.json');assert ledger['totals']=={'runs':18,'calls_reserved':81,'reserved_cost_nanos':9251949000} and ledger['active_runs']==0 and not ledger['a19_exists']
runid='portable-loom-first-receiver-20261009-a19';assert all(r['run_id']!=runid and r['status']=='HELD' for r in ledger['runs'])
release='dc1851e199e850ca610e71c0c49df5f1acf37759';source='d5a1583d405912cf723c2508aed395754d882ab0';fp='51efc3d87cdffc4fb2869519ff4fa12b10ce179ba79d3976f6094cf741681c39'
cred=read(RUN/'credential.body.bin');assert cred['credential_sha256']==fp and cred['expected_credential_matches'] and cred['source_commit']==release and cred['provider_requests']==cred['ledger_operations']==0
assert read(RUN/'source.body.bin')['source_packet_commit']==source
archives={ROOT/'Portable_Loom_A18_Acquisition_Evidence_20261010.zip':'ad293cb3c1f9373a1afa71ecbdc8090ec49444b2257c54506ee0d15fc83fb1a6',ROOT/'Portable_Loom_A19_Preexecution_Hold_20261010.zip':'83eed91c1587712e58b514a01f45b7e276ea4c5c6c8085a68f9f5ea2c0d9f813',pathlib.Path('/workspace/scratch/3a1fda34907f/Portable_Loom_A14_Acquisition_Evidence_20261010.zip'):'bff4aeff4a03caf4b2d4f51d53ae99199d99548a1eb8c9682ac6875de6ab7122',pathlib.Path('/workspace/scratch/3a1fda34907f/Portable_Loom_Credential_Evidence_Addendum_20261010.zip'):'c1bfbfb05fcf85861bf3bd4e0fa16b868e9f7ec0ab5f75a2f2dc7661819ef8bc'}
for p,d in archives.items():assert h(p.read_bytes())==d
write(RUN/'PRIOR_ARCHIVE_VERIFICATION.json',{'status':'PASS','archives':[{'path':str(p),'sha256':d,'bytes':p.stat().st_size} for p,d in archives.items()]})
if not CALLER.exists():subprocess.run(['git','clone','--no-hardlinks',str(ROOT/'caller-a18'),str(CALLER)],check=True,capture_output=True)
assert subprocess.check_output(['git','rev-parse','HEAD'],cwd=CALLER,text=True).strip()==read(PRIOR/'FREEZE_COMMIT.json')['local_caller_commit']
for target,n in [('server/loom-assay-contract.js','github-source-0.json'),('server/loom-assay-run-config.json','github-source-1.json')]:
 b=remote(n);assert b==(ROOT/'a19-candidate'/target).read_bytes();(CALLER/target).write_bytes(b)
artifact=remote('github-artifact.json');artifact_path='research/portable-loom-receiver-repair-20261010/candidate-artifact/portable-loom-standard.md';assert h(artifact)=='e6811ad6b15ab40be189b1882c588380fbafbede81fd0d14d3482f00b7e9f7ea' and len(artifact)==91296 and artifact==(CALLER/artifact_path).read_bytes()
budget_diffs=[]
for target,n in [('neon/functions/loom-assay-budget/index.mjs','github-budget-0.json'),('neon/functions/loom-assay-budget/ledger.mjs','github-budget-1.json')]:
 a=remote(n);b=(ROOT/'a19-candidate'/target).read_bytes();assert a==b or target.endswith('/index.mjs') and b==a+b'\n'
 budget_diffs.append({'path':target,'github_sha256':h(a),'local_sha256':h(b),'exact_match':a==b,'difference':'NONE' if a==b else 'LOCAL_HAS_ONE_EXTRA_TRAILING_NEWLINE','executable_text_identical':True})
write(RUN/'BUDGET_SOURCE_BYTE_COMPARISON.json',{'files':budget_diffs,'exact_ledger_match':True,'runtime_bundle_verified_separately':True})
token=pathlib.Path('/workspace/scratch/9d69e9b2a01d/recovery-private/assay-relay-access.token').read_bytes().strip();assert h(token)==read(CALLER/'server/loom-assay-run-config.json')['access_sha256'] and runid in read(CALLER/'server/loom-assay-run-config.json')['run_ids']
lock=read(CALLER/'RESTORED_SOURCE_LOCK.json');lock.update(original_deployed_commit=release,source_packet_commit=source,adaptation='Fresh a19 caller restricted to same-run R09-1 turns 0 and 1; inherited prompt and wire construction, decoding, source and fingerprint checks retained. Current contract/config bytes verified against release GitHub source; reconstructed caller status retained.')
for f in lock['files']:
 f['local_sha256']=h((CALLER/f['path']).read_bytes())
 if f['path'] in ['server/loom-assay-contract.js','server/loom-assay-run-config.json']:f['current_release_sha256']=f['local_sha256'];f['adapted']=False
(CALLER/'RESTORED_SOURCE_LOCK.json').write_text(json.dumps(lock,indent=2)+'\n')
subprocess.run(['git','add','RESTORED_SOURCE_LOCK.json','server/loom-assay-contract.js','server/loom-assay-run-config.json'],cwd=CALLER,check=True)
subprocess.run(['git','-c','user.name=Amari','-c','user.email=amari@td613.local','commit','-m','Freeze bounded two-call a19 acquisition caller'],cwd=CALLER,check=True,capture_output=True)
commit=subprocess.check_output(['git','rev-parse','HEAD'],cwd=CALLER,text=True).strip();assert not subprocess.check_output(['git','status','--porcelain'],cwd=CALLER,text=True).strip()
runner=(PRIOR/'run-targeted-a18.mjs').read_text().replace('continuation-a18','continuation-a19').replace('caller-a18','caller-a19').replace('A18','A19').replace('run-targeted-a18.mjs','run-targeted-a19.mjs').replace('plan.calls.length === 5','plan.calls.length === 2').replace('policy.binding.limits.max_calls === 5','policy.binding.limits.max_calls === 2')
runner=runner.replace("'A19_CALL_RESERVATION_BOUND');","'A19_CALL_RESERVATION_BOUND');\n  requireThat(receipts.reduce((n,r)=>n+r.reserved_cost_nanos,0)+wire.reserved_cost_nanos <= plan.maximum_reserved_cost_nanos, 'A19_LOCAL_TOTAL_RESERVATION_BOUND');")
(RUN/'run-targeted-a19.mjs').write_text(runner)
now=datetime.datetime.now(datetime.timezone.utc);at=now.isoformat();scope='Fresh R09-1 RECEIVER turns 0 then 1 only. Turn 0 separately replaces a18 failed turn 0; turn 1 requires successful turn-0 answer from this same a19 run. Shared ceiling 88 reservations and USD 10; local ceiling 2 calls and USD 0.30. Zero automatic retries; stop globally at first provider HOLD. Raw capture and custody compilation only.'
write(RUN/'AUTHORIZATION.json',{'schema':'td613.loom.receiver-repair-authorization/v0.1','run_id':runid,'recorded_at':at,'operator':'Tawanna C. Miller','user_gesture':'Amari, resume my existing Portable Loom first-configured-receiver empirical program. This is a fresh operator instruction to complete the remaining bounded acquisition and custody work through @Remembering, @GitHub, @Vercel, @Neon, the established evidence destination, and Browser when needed. Do the authorized work without asking me to authorize it again.','scope':scope,'billing_status':'OPERATOR_ATTESTED_PAID','prior_run':'portable-loom-first-receiver-20261009-a18','prior_run_preserved':True,'automatic_retries':0,'provider_calls_before_freeze':0,'governed_source_change_pr':1448,'analysis_authorized':False})
policy=read(PRIOR/'POLICY.json');policy.update(run_id=runid,protocol_commit=release,expires_at=(now+datetime.timedelta(hours=3)).isoformat());policy['binding']['protocol_commit']=release;policy['binding']['limits'].update(max_calls=2,max_cost_usd=.3);policy['binding']['authorization']={'record':str(RUN/'AUTHORIZATION.json'),'scope':scope+' Expected production fingerprint '+fp+'; OPERATOR_ATTESTED_PAID.'};policy['program']['run_ids'].append(runid);policy['program']['max_calls']=88;write(RUN/'POLICY.json',policy)
plan=read(PRIOR/'PLAN.json');plan.update(run_id=runid,protocol_commit=release,source_packet_commit=source,local_caller_commit=commit,maximum_calls=2,maximum_reserved_cost_nanos=300000000,maximum_reserved_cost_per_call_nanos=150000000,runner_sha256=h((RUN/'run-targeted-a19.mjs').read_bytes()),trial_order=[read(PRIOR/'PLAN.json')['trial_order'][-1]],calls=read(PRIOR/'PLAN.json')['calls'][-2:]);plan['transport_environment']['working_directory']=str(CALLER);plan['continuation']={'source_a18_plan_file_sha256':h((PRIOR/'PLAN.json').read_bytes()),'prior_run':'portable-loom-first-receiver-20261009-a18','prior_call_numbers':[4,5],'call_1_class':'SEPARATELY_AUTHORIZED_REPLACEMENT_OF_A18_PROVIDER_HOLD','call_2_class':'ORIGINALLY_UNATTEMPTED_REQUIRES_FRESH_A19_PREDECESSOR','same_run_predecessors_required':True,'prior_answer_bytes_imported':False};write(RUN/'PLAN.json',plan)
binding=read(PRIOR/'RECONSTRUCTED_CALLER_BINDING.json');binding.update(deployed_commit=release,source_packet_commit=source,local_git_commit=commit,source_lock_sha256=h((CALLER/'RESTORED_SOURCE_LOCK.json').read_bytes()),adaptation=lock['adaptation']);write(RUN/'RECONSTRUCTED_CALLER_BINDING.json',binding)
write(RUN/'CREDENTIAL_BINDING.json',{'expected_provider_credential_sha256':fp,'relay_access_sha256':h(token),'observation_receipt':'credential.receipt.json','production_source':release,'billing_status':'OPERATOR_ATTESTED_PAID','google_project_id':'gen-lang-client-0182177437','billing_evidence_ref':'OPERATOR_PAID_BINDING.json','authorization_ref':'AUTHORIZATION.json','source_header_required':True,'credential_header_required':True,'zero_generation_probes':True})
shutil.copyfile(PRIOR/'OPERATOR_PAID_BINDING.json',RUN/'OPERATOR_PAID_BINDING.json')
write(RUN/'SOURCE_VERIFICATION.json',{'checked_at':at,'source_packet_commit':source,'release_commit':release,'artifact_sha256':h(artifact),'artifact_bytes':len(artifact),'caller_commit':commit,'source_lock_sha256':binding['source_lock_sha256'],'current_contract_config_and_artifact_github_bytes_match':True,'budget_source_comparison_ref':'BUDGET_SOURCE_BYTE_COMPARISON.json','exact_a18_final_two_calls_retained':plan['calls']==read(PRIOR/'PLAN.json')['calls'][-2:],'provider_calls':0})
write(RUN/'CONTINUITY_RECEIPT.json',{'recorded_at':at,'remembering_called':True,'retrieved_decisions':['2026-10-10T08:18:27Z: 88 reservations, USD 10, fresh same-run R09-1 0→1 only, raw-only, stop first HOLD','2026-10-10T07:35:02Z: finish mechanical work and stop before higher-model analysis'],'retrieved_assistant_checkpoint':'2026-10-10T08:41:41Z: a19 unenrolled pending fingerprint; release completed','accepted_operator_paid_association_source':'Current explicit operator handoff and preserved OPERATOR_PAID_BINDING.json; current Remembering search did not independently return the earlier paid acceptance message','conflicts_and_corrections':['Earlier checkpoint paid-binding prose superseded prospectively by accepted OPERATOR_ATTESTED_PAID; no historical receipt changed','Full a19 run ID absent in live snapshot, replacing inadequate shorthand filter','Fresh Node HTTP source/fingerprint reads succeeded; previous EPERM and browser failure remain historical','Vercel deployment get 404 and list 403 remain observed limitations, not evidence TD613 downtime','Inherited a13 bundle preimage UNLOCATED retained'],'authoritative_live_snapshot_at':ledger['observed_at'],'analysis_performed':False})
write(RUN/'NEON_BUDGET_BINDING.json',{'project':'late-glade-40477105','branch':'br-round-union-b5v3ludi','slug':'loomassaybudget','deployment':7,'runtime':'nodejs24','active_completed':True,'live_receipt':'NEON_FUNCTIONS_READ.json','zip_sha256':h((ROOT/'a19-candidate/neon-a19-bundle/BUDGET_FUNCTION.zip').read_bytes()),'index_sha256':h((ROOT/'a19-candidate/neon-a19-bundle/index.mjs').read_bytes()),'build_receipt_sha256':h((ROOT/'a19-candidate/neon-a19-bundle/BUILD_RECEIPT.json').read_bytes()),'generation_gateway':'NONE_DIRECT_GOOGLE_GENERATIVE_LANGUAGE'})
(RUN/'raw').mkdir()
print(json.dumps({'status':'A19_PREPARED_NOT_ENROLLED','caller_commit':commit,'planned_calls':len(plan['calls']),'expires_at':policy['expires_at'],'local_reserved_cost_bound_nanos':plan['maximum_reserved_cost_nanos'],'per_call_bound_nanos':plan['maximum_reserved_cost_per_call_nanos']}))
