{
  "schema": "td613.pedagogue.dependency-edge-admission-witness-source-origin-custody-execution-receipt/v0.1",
  "candidate": "E8_DEPENDENCY_EDGE_ADMISSION_WITNESS_SOURCE_ORIGIN_CUSTODY",
  "assay": "Return Address",
  "candidate_status": "ATTACK_ONLY_NOT_PROMOTED",
  "parent_e7_receipt": "6200e9b86844e23692fe125cd3d10df47b14ffab",
  "preregistration_commit": "ad009c6dd3d0a93b5a42bd2c9eab167c021b8403",
  "evaluator_commit": "ebfbda5ddefc74970806488960f8fbd373dcb8e3",
  "science_head": "aa385c1108d0528f57f7ca7e24e0a772e8226add",
  "workflow": {
    "name": "TD613 Consolidated Validation",
    "run_number": 1924,
    "run_id": 32546722351,
    "static_job_id": 96966379006,
    "static_job_status": "SUCCESS",
    "a15_r0_step_18_status": "SUCCESS",
    "full_repository": "SKIPPED",
    "self_hosted": "SKIPPED",
    "front_line_browser": "SKIPPED",
    "giving_practice_browser": "SKIPPED",
    "full_product_browser": "SKIPPED"
  },
  "result_provenance": "LITERAL_CI_STDOUT_RECOVERED",
  "literal_stdout_block_recovered": true,
  "inherited_e7_verdict": "DEPENDENCY_EDGE_ADMISSION_WITNESS_NON_ANTICIPATING_ACQUISITION_CUSTODY_CANDIDATE_SURVIVES_BOUNDED_CLERK_WAS_ALREADY_THERE",
  "inherited_e7_source_origin_verdict": "E7_SOURCE_ORIGIN_INSUFFICIENCY_ESTABLISHED",
  "candidate_verdict": "DEPENDENCY_EDGE_ADMISSION_WITNESS_SOURCE_ORIGIN_CUSTODY_CANDIDATE_SURVIVES_BOUNDED_RETURN_ADDRESS",
  "defeat_conditions": [],
  "observed_stdout": {
    "RA01_e7_status": "ADMIT_NON_ANTICIPATING_DEPENDENCY_EDGE_ADMISSION_WITNESS",
    "RA01_e8_status": "REFUSE_SOURCE_ORIGIN_UNIDENTIFIED",
    "RA01_W2": "REFUSE_CURRENT_WARRANT_NO_ACTIVE_LAWFUL_SUPPORT",
    "RA02_status": "ADMIT_SYNTHETIC_SOURCE_ORIGIN_BOUND_WITNESS",
    "RA02_W2": "ADMIT_CURRENT_WARRANT_WITH_TRANSITIVE_LAWFUL_SUPPORT",
    "RA03_status": "REFUSE_SOURCE_ORIGIN_INTERNAL_SELF_ATTESTATION",
    "RA04_status": "REFUSE_SOURCE_ORIGIN_TARGET_MISMATCH",
    "RA05_status": "ABSTAIN_SOURCE_ORIGIN_ANCHOR_STALE",
    "RA06_status": "ABSTAIN_CONFLICTING_SOURCE_ORIGIN_ANCHORS",
    "RA07_invariant": true,
    "RA08_duplicate_amplification": false,
    "RA09_status": "REFUSE_SOURCE_ORIGIN_INTERNAL_SELF_ATTESTATION",
    "RA10_status": "REFUSE_E7_NON_ANTICIPATING_ACQUISITION_INVALID",
    "RA11_status": "REFUSE_UNACCEPTED_SOURCE_ORIGIN_CLASS",
    "RA12_status": "ADMIT_SYNTHETIC_SOURCE_ORIGIN_BOUND_WITNESS"
  },
  "claim_ceiling": [
    "admitted synthetic source-origin anchor != authenticated live source",
    "admitted synthetic source-origin anchor != source honesty",
    "admitted synthetic source-origin anchor != physical source origin",
    "admitted synthetic source-origin anchor != unbiased sampling",
    "admitted synthetic source-origin anchor != institutional independence",
    "admitted synthetic source-origin anchor != real-world chronology"
  ],
  "next_learning_action_if_survives": "STOP_SYNTHETIC_SOURCE_ORIGIN_LANE_AND_REQUIRE_NEW_HUMAN_GESTURE_FOR_LIVE_EXTERNAL_SOURCE_OBSERVABILITY",
  "next_synthetic_source_origin_mutation": "NOT_EARNED",
  "live_external_source_observability": "HUMAN_GESTURE_REQUIRED",
  "real_institutional_attestation": "HUMAN_GESTURE_REQUIRED",
  "intersection_program": "HUMAN_GESTURE_REQUIRED",
  "live_external_source_adapter": false,
  "external_source_authenticated": false,
  "external_physical_origin_claim": false,
  "source_honesty_claim": false,
  "unbiased_sampling_claim": false,
  "institutional_independence_claim": false,
  "real_world_chronology_claim": false,
  "universal_graph_semantics": false,
  "H2": "HELD_NOT_TESTED_HERE",
  "H3": "HELD_NOT_TESTED_HERE",
  "intersections": "HELD_NOT_OPENED_HERE",
  "APERTURE_V32_REPLAY_STABILITY": "HELD_NOT_YET_WITNESSED",
  "promotion_authority": false,
  "product_mutation": false,
  "shared_pedagogue_engine_mutation": false,
  "workflow_mutation": false,
  "browser_execution": false,
  "merge_performed": false,
  "deployment_performed": false,
  "release_authority": false,
  "vercel_release_requires_issue_405_and_new_explicit_operator_gesture": true
}
