{
  "schema": "td613.pedagogue.exogenous-anchor-revision-episode-custody-hostile-preregistration/v0.1",
  "research_surface": "PR#677",
  "candidate": "E2_EXOGENOUS_ANCHOR_REVISION_EPISODE_CUSTODY",
  "display_name": "Exogenous Anchor Revision Episode Custody",
  "assay": "Moving Sash",
  "candidate_status": "ATTACK_ONLY_NOT_PROMOTED",
  "presumption_of_survival": false,
  "inherited_e1_verdict": "EXOGENOUS_ANCHOR_ADMISSION_CUSTODY_CANDIDATE_SURVIVES_BOUNDED_OPEN_WINDOW",
  "inherited_e1_jurisdiction_preserved": true,
  "e1_revision_custody_overclaim_asserted": false,
  "strong_falsifier": {
    "same_current_e1_observation": true,
    "continuous_episode_count": 1,
    "interrupted_episode_count": 2,
    "revision_history_must_differ": true
  },
  "allowed_revision_kinds": [
    "ADMIT",
    "WITHDRAW",
    "REINTRODUCE",
    "RENAME_CONTINUOUS",
    "REPLACE_SEMANTIC"
  ],
  "rooms": [
    "MS01_SAME_VIEW_DIFFERENT_HISTORY",
    "MS02_OLD_PANE_REPLACED",
    "MS03_NEW_NAME_SAME_PANE",
    "MS04_CLOSED_AND_REOPENED",
    "MS05_TWO_HANDS_ON_SASH",
    "MS06_REVISION_NAMEPLATE_SHUFFLE",
    "MS07_DUPLICATE_REPAIR_TICKET",
    "MS08_YESTERDAY_CANNOT_OVERRULE_TODAY",
    "MS09_REVOKED_VIEW",
    "MS10_SNAPSHOT_PHOTOGRAPH",
    "MS11_POSTHOC_CARPENTER",
    "MS12_E1_STILL_SEES_THROUGH_GLASS"
  ],
  "defeat_conditions": [
    "SAME_CURRENT_OBSERVATION_ERASES_REVISION_HISTORY",
    "SEMANTIC_REPLACEMENT_INHERITS_OLD_AUTHORITY_WITHOUT_CONTINUITY",
    "CONTINUOUS_RENAME_CREATES_FALSE_NEW_EPISODE",
    "REINTRODUCTION_ERASES_SUPPORT_GAP",
    "CONFLICTING_SAME_EPOCH_REVISION_FORCED_BY_IDENTIFIER",
    "REVISION_IDENTIFIER_OR_SERIALIZATION_CHANGES_AUTHORITY",
    "DUPLICATE_REVISION_AMPLIFIES_HISTORY_OR_CONFIDENCE",
    "OLDER_REVISION_OVERRIDES_NEWER_SEMANTIC_EPOCH",
    "WITHDRAWN_ANCHOR_RETAINS_CURRENT_E1_AUTHORITY",
    "CURRENT_SNAPSHOT_OVERCLAIMS_REVISION_HISTORY",
    "SEALED_REVISION_LEDGER_MUTATED",
    "E2_CHANGES_E1_CURRENT_SCOPED_ADMISSION_SEMANTICS"
  ],
  "survival_verdict": "EXOGENOUS_ANCHOR_REVISION_EPISODE_CUSTODY_CANDIDATE_SURVIVES_BOUNDED_MOVING_SASH",
  "falsification_verdict": "EXOGENOUS_ANCHOR_REVISION_EPISODE_CUSTODY_CANDIDATE_FALSIFIED_IN_BOUNDED_MOVING_SASH",
  "synthetic_exogenous_fixture": true,
  "live_external_source_adapter": false,
  "real_world_external_provenance_claim": false,
  "H2": "HELD_NOT_TESTED_HERE",
  "H3": "HELD_NOT_TESTED_HERE",
  "intersections": "HELD_NOT_OPENED_HERE",
  "APERTURE_V32_REPLAY_STABILITY": "HELD_NOT_YET_WITNESSED",
  "promotion_authority": false,
  "product_mutation": false,
  "shared_pedagogue_engine_mutation": false,
  "workflow_mutation": false,
  "browser_execution": false,
  "merge_performed": false,
  "deployment_performed": false,
  "release_authority": false,
  "vercel_release_requires_issue_405_and_new_explicit_operator_gesture": true
}
