{
  "schema": "td613.pedagogue.dependency-edge-admission-witness-source-origin-custody-hostile/v0.1",
  "candidate": "E8_DEPENDENCY_EDGE_ADMISSION_WITNESS_SOURCE_ORIGIN_CUSTODY",
  "assay": "Return Address",
  "parent_e7_receipt": "6200e9b86844e23692fe125cd3d10df47b14ffab",
  "candidate_status": "ATTACK_ONLY_NOT_PROMOTED",
  "presumption_of_survival": false,
  "required_origin_field": "SOURCE_ORIGIN_CLASS",
  "required_origin_value": "ADMITTED_EXTERNAL_ORIGIN",
  "strong_falsifier": {
    "same_pre_proposal_witness_and_proposal": true,
    "e7_required_status": "ADMIT_NON_ANTICIPATING_DEPENDENCY_EDGE_ADMISSION_WITNESS",
    "missing_origin_required_e8_status": "REFUSE_SOURCE_ORIGIN_UNIDENTIFIED",
    "matching_origin_required_e8_status": "ADMIT_SYNTHETIC_SOURCE_ORIGIN_BOUND_WITNESS",
    "e7_source_origin_insufficiency_required": true
  },
  "rooms": [
    "RA01_NO_RETURN_ADDRESS",
    "RA02_REGISTERED_RETURN_ADDRESS",
    "RA03_ADDRESS_WRITTEN_BY_THE_OCCUPANT",
    "RA04_RIGHT_STREET_WRONG_HOUSE",
    "RA05_YESTERDAYS_POSTMARK",
    "RA06_TWO_RETURN_ADDRESSES",
    "RA07_BRASS_NAMEPLATE_SHUFFLE",
    "RA08_DUPLICATE_POSTAGE",
    "RA09_EXTERNAL_WRITTEN_IN_CRAYON",
    "RA10_LATE_CLERK_WITH_PERFECT_RETURN_ADDRESS",
    "RA11_REGISTERED_INTERNAL_ORIGIN",
    "RA12_LAMINATED_RETURN_CARD"
  ],
  "claim_ceiling": [
    "admitted synthetic source-origin anchor != authenticated live source",
    "admitted synthetic source-origin anchor != source honesty",
    "admitted synthetic source-origin anchor != physical origin",
    "admitted synthetic source-origin anchor != institutional independence",
    "admitted synthetic source-origin anchor != real-world chronology"
  ],
  "live_external_source_adapter": false,
  "source_authenticated": false,
  "source_honesty": "HELD",
  "physical_origin": "HELD",
  "institutional_independence": "HELD",
  "external_chronology": "HELD",
  "next_learning_action_if_survives": "STOP_SYNTHETIC_SOURCE_ORIGIN_LANE_AND_REQUIRE_NEW_HUMAN_GESTURE_FOR_LIVE_EXTERNAL_SOURCE_OBSERVABILITY",
  "H2": "HELD_NOT_TESTED_HERE",
  "H3": "HELD_NOT_TESTED_HERE",
  "intersections": "HELD_NOT_OPENED_HERE",
  "APERTURE_V32_REPLAY_STABILITY": "HELD_NOT_YET_WITNESSED",
  "promotion_authority": false,
  "product_mutation": false,
  "shared_pedagogue_engine_mutation": false,
  "workflow_mutation": false,
  "browser_execution": false,
  "merge_performed": false,
  "deployment_performed": false,
  "release_authority": false,
  "vercel_release_requires_issue_405_and_new_explicit_operator_gesture": true
}
