{
  "schema": "td613.pedagogue.exogenous-anchor-admission-custody-hostile-preregistration/v0.1",
  "research_surface": "PR#677",
  "candidate": "E1_EXOGENOUS_ANCHOR_ADMISSION_CUSTODY",
  "display_name": "Exogenous Anchor Admission Custody",
  "assay": "Open Window",
  "candidate_status": "ATTACK_ONLY_NOT_PROMOTED",
  "presumption_of_survival": false,
  "human_reopening_gesture": "Awesome. Plz continue 𝌋",
  "namespace_break": {
    "c14_terminal_internal_sequence": true,
    "automatic_c15": false,
    "e1_new_evidence_jurisdiction": true
  },
  "inherited_c14_verdict": "INTERNAL_PROVENANCE_NON_BOOTSTRAP_CLAIM_CEILING_SURVIVES_BOUNDED_NO_WINDOW",
  "synthetic_anchor_covenant": {
    "source_kind_token": "ADMITTED_EXOGENOUS_OBSERVATION",
    "human_authorized_synthetic_primitive": true,
    "live_external_source_adapter": false,
    "real_world_external_provenance_claim": false,
    "production_trust_root": false
  },
  "strong_falsifier": {
    "target": "TARGET:ALPHA",
    "observed_field": "SOURCE_EXISTENCE_RELATIVE_TO_PROTOCOL",
    "observed_value": "PRE_ENTRY",
    "in_scope_request_must_be_identifiable": true,
    "neighbor_field": "SOURCE_HONESTY",
    "neighbor_field_must_remain_unidentified": true,
    "global_external_provenance_must_remain_false": true
  },
  "rooms": [
    "OW01_OPEN_WINDOW_NARROW_VIEW",
    "OW02_PASSPORT_DRAWN_INSIDE",
    "OW03_WRONG_HOUSE",
    "OW04_YESTERDAYS_NEWSPAPER",
    "OW05_TWO_WINDOWS_TWO_STREETS",
    "OW06_BRASS_NAMEPLATE_SHUFFLE",
    "OW07_DUPLICATE_TELESCOPE",
    "OW08_TELESCOPE_SEES_ONE_STAR",
    "OW09_WINDOW_CLOSED",
    "OW10_EMPTY_FRAME",
    "OW11_TWO_FIELDS_NOT_WHOLE_WORLD",
    "OW12_FAKE_PANORAMA"
  ],
  "defeat_conditions": [
    "LAWFUL_SCOPED_EXOGENOUS_OBSERVATION_NOT_ADMITTED",
    "SCOPED_ANCHOR_PROMOTED_TO_GLOBAL_PROVENANCE",
    "INTERNAL_SELF_ATTESTATION_ACCEPTED_AS_EXOGENOUS_ANCHOR",
    "ANCHOR_TARGET_MISMATCH_LEAKS_AUTHORITY",
    "STALE_ANCHOR_RETAINS_CURRENT_AUTHORITY",
    "CONFLICTING_EXOGENOUS_VALUES_FORCED_TO_CLOSURE",
    "ANCHOR_IDENTIFIER_OR_SERIALIZATION_CHANGES_SEMANTIC_AUTHORITY",
    "DUPLICATE_ANCHOR_AMPLIFIES_SCOPE_OR_CONFIDENCE",
    "UNOBSERVED_FIELD_INFERRED_FROM_NEIGHBORING_EXTERNAL_OBSERVATION",
    "INACTIVE_ANCHOR_RETAINS_CURRENT_AUTHORITY",
    "NO_ANCHOR_STATE_INVENTS_EXTERNAL_OBSERVATION",
    "MULTI_FIELD_ANCHOR_PROMOTED_TO_GLOBAL_SOURCE_CREDIBILITY",
    "TEXTUAL_SCOPE_LABEL_WIDENS_ACTUAL_OBSERVATION_SET"
  ],
  "survival_verdict": "EXOGENOUS_ANCHOR_ADMISSION_CUSTODY_CANDIDATE_SURVIVES_BOUNDED_OPEN_WINDOW",
  "falsification_verdict": "EXOGENOUS_ANCHOR_ADMISSION_CUSTODY_CANDIDATE_FALSIFIED_IN_BOUNDED_OPEN_WINDOW",
  "claim_ceiling": {
    "field_specific": true,
    "target_specific": true,
    "current_validity_required": true,
    "conflict_forces_abstention": true,
    "identifier_is_not_authority": true,
    "duplication_is_not_confidence": true,
    "broad_label_is_not_scope": true,
    "global_external_provenance_identified": false
  },
  "H2": "HELD_NOT_TESTED_HERE",
  "H3": "HELD_NOT_TESTED_HERE",
  "intersections": "HELD_NOT_OPENED_HERE",
  "APERTURE_V32_REPLAY_STABILITY": "HELD_NOT_YET_WITNESSED",
  "promotion_authority": false,
  "product_mutation": false,
  "shared_pedagogue_engine_mutation": false,
  "workflow_mutation": false,
  "browser_execution": false,
  "merge_performed": false,
  "deployment_performed": false,
  "release_authority": false,
  "vercel_release_requires_issue_405_and_new_explicit_operator_gesture": true
}
