{
  "schema": "td613.pedagogue.dependency-edge-admission-witness-non-anticipating-acquisition-custody-hostile/v0.1",
  "candidate": "E7_DEPENDENCY_EDGE_ADMISSION_WITNESS_NON_ANTICIPATING_ACQUISITION_CUSTODY",
  "assay": "Clerk Was Already There",
  "parent_e6_receipt": "99a080f75973c00dc7633c42b62609b7cb391168",
  "candidate_status": "ATTACK_ONLY_NOT_PROMOTED",
  "presumption_of_survival": false,
  "strong_falsifier": {
    "same_witness_material_pre_and_post_proposal": true,
    "raw_e6_required_to_admit_post_proposal_material": true,
    "e7_required_pre_status": "ADMIT_NON_ANTICIPATING_DEPENDENCY_EDGE_ADMISSION_WITNESS",
    "e7_required_post_status": "REFUSE_POST_PROPOSAL_DEPENDENCY_EDGE_ADMISSION_WITNESS",
    "inherited_e6_insufficiency_required": true
  },
  "required_protocol": {
    "recognized_acquisition_episode": true,
    "recognized_dependency_edge_admission_proposal": true,
    "acquisition_must_precede_proposal": true,
    "visible_field_clone_is_authority": false,
    "proposal_identifier_is_authority": false,
    "witness_identifier_is_authority": false,
    "admission_identifier_is_authority": false,
    "serialization_order_is_authority": false,
    "sequence_distance_is_confidence": false
  },
  "rooms": [
    "CA01_CLERK_WAS_ALREADY_THERE",
    "CA02_PHOTOCOPIED_INTAKE_TICKET",
    "CA03_ERASED_INTAKE_BOOK",
    "CA04_PROPOSAL_NUMBER_CHANGED",
    "CA05_BADGE_NUMBERS_CHANGED",
    "CA06_FOLDER_REORDERED",
    "CA07_EMPTY_PERMIT_FOLDER",
    "CA08_EARLY_BUT_WRONG_CLERK",
    "CA09_EARLY_BUT_RECANTED_CLERK",
    "CA10_ONE_EARLY_CLERK_ONE_LATE_PLANT",
    "CA11_LONG_HALLWAY",
    "CA12_LOCKED_PROPOSAL_FOLDER"
  ],
  "claim_ceiling": [
    "protocol acquisition before protocol proposal != external physical acquisition time",
    "protocol acquisition before protocol proposal != source honesty",
    "protocol acquisition before protocol proposal != unbiased sampling",
    "protocol acquisition before protocol proposal != institutional independence",
    "protocol acquisition before protocol proposal != real-world chronology"
  ],
  "external_source_honesty": "HELD",
  "physical_acquisition_time": "HELD",
  "institutional_independence": "HELD",
  "external_chronology": "HELD",
  "next_learning_action_if_survives": "ATTACK_ACQUISITION_SOURCE_ORIGIN_PROVENANCE_BEFORE_LARGER_GRAPH_FORMALISM",
  "H2": "HELD_NOT_TESTED_HERE",
  "H3": "HELD_NOT_TESTED_HERE",
  "intersections": "HELD_NOT_OPENED_HERE",
  "APERTURE_V32_REPLAY_STABILITY": "HELD_NOT_YET_WITNESSED",
  "promotion_authority": false,
  "product_mutation": false,
  "shared_pedagogue_engine_mutation": false,
  "workflow_mutation": false,
  "browser_execution": false,
  "merge_performed": false,
  "deployment_performed": false,
  "release_authority": false,
  "vercel_release_requires_issue_405_and_new_explicit_operator_gesture": true
}
