{
  "schema": "td613.pedagogue.dependency-edge-admission-witness-custody-execution-receipt/v0.1",
  "candidate": "E6_DEPENDENCY_EDGE_ADMISSION_WITNESS_CUSTODY",
  "assay": "Permit Printer",
  "candidate_status": "ATTACK_ONLY_NOT_PROMOTED",
  "parent_e5_receipt": "aad36619a0e8720644754c5772fff0a5c092f8f6",
  "preregistration_commit": "823b3a79d0c14d7d5ac90be7c1b31da21be7a285",
  "evaluator_commit": "57dd675708bb8cbcd6337289b2f22ea8007b2a53",
  "science_head": "f97e728eb7e7732a7098f7d8c391425bd06c1d22",
  "workflow": {
    "name": "TD613 Consolidated Validation",
    "run_number": 1920,
    "run_id": 32545714484,
    "static_job_status": "SUCCESS",
    "a15_r0_step_18_status": "SUCCESS",
    "full_repository": "SKIPPED",
    "self_hosted": "SKIPPED",
    "front_line_browser": "SKIPPED",
    "giving_practice_browser": "SKIPPED",
    "full_product_browser": "SKIPPED"
  },
  "result_provenance": "SOURCE_RECONSTRUCTED_FROM_EXACT_WITNESSED_SCIENCE_HEAD",
  "literal_stdout_block_recovered": false,
  "inherited_e5_admission_ledger_provenance_verdict": "E5_ADMISSION_LEDGER_PROVENANCE_INSUFFICIENCY_ESTABLISHED",
  "candidate_verdict": "DEPENDENCY_EDGE_ADMISSION_WITNESS_CUSTODY_CANDIDATE_SURVIVES_BOUNDED_PERMIT_PRINTER",
  "defeat_conditions": [],
  "strong_falsifier": {
    "e5_edge_status": "ADMIT_LEDGER_BOUND_DEPENDENCY_EDGE",
    "e5_W2_status": "ADMIT_CURRENT_WARRANT_WITH_TRANSITIVE_LAWFUL_SUPPORT",
    "e6_permit_status": "REFUSE_SELF_ATTESTED_DEPENDENCY_EDGE_ADMISSION",
    "e6_W2_status": "REFUSE_CURRENT_WARRANT_NO_ACTIVE_LAWFUL_SUPPORT"
  },
  "claim_ceiling": [
    "matching witness-ledger record != non-anticipating acquisition",
    "matching witness-ledger record != predeclared witness protocol",
    "matching witness-ledger record != independent institutional authority"
  ],
  "witness_acquisition_provenance": "HELD_FOR_NEXT_ATTACK",
  "pre_admission_witness_protocol": "HELD_FOR_NEXT_ATTACK",
  "next_learning_action_if_survives": "ATTACK_ADMISSION_WITNESS_ACQUISITION_PROVENANCE_AND_PRE_ADMISSION_PROTOCOL_BEFORE_LARGER_GRAPH_COMPOSITION",
  "synthetic_exogenous_fixture": true,
  "live_external_source_adapter": false,
  "real_world_external_provenance_claim": false,
  "real_world_authorization_claim": false,
  "H2": "HELD_NOT_TESTED_HERE",
  "H3": "HELD_NOT_TESTED_HERE",
  "intersections": "HELD_NOT_OPENED_HERE",
  "APERTURE_V32_REPLAY_STABILITY": "HELD_NOT_YET_WITNESSED",
  "promotion_authority": false,
  "product_mutation": false,
  "shared_pedagogue_engine_mutation": false,
  "workflow_mutation": false,
  "browser_execution": false,
  "merge_performed": false,
  "deployment_performed": false,
  "release_authority": false,
  "vercel_release_requires_issue_405_and_new_explicit_operator_gesture": true
}
