{
  "schema": "td613.pedagogue.dependency-edge-admission-provenance-custody-execution-receipt/v0.1",
  "date": "2026-08-21",
  "research_surface": "PR#677",
  "candidate": "E5_DEPENDENCY_EDGE_ADMISSION_PROVENANCE_CUSTODY",
  "assay": "Unlicensed Electrician",
  "candidate_status": "BOUNDED_CANDIDATE_SURVIVED_NOT_PROMOTED",
  "inherited_e4_declared_edge_admission_verdict": "E4_DECLARED_DEPENDENCY_EDGE_ADMISSION_INSUFFICIENCY_ESTABLISHED",
  "verdict": "DEPENDENCY_EDGE_ADMISSION_PROVENANCE_CUSTODY_CANDIDATE_SURVIVES_BOUNDED_UNLICENSED_ELECTRICIAN",
  "defeat_conditions": [],
  "lineage": {
    "e4_receipt": "72e13c85381ca5505eb5958e08c1afa012324152",
    "e5_preregistration": "598e9edf77b36962150d12e77a5fbb23803719bc",
    "e5_evaluator": "442eeeadb0b494d2132066564a85815d03e0fa80",
    "e5_science_head": "10045c671a0afd711ef2ccc26b7c7c76b871e235"
  },
  "witness": {
    "workflow": "TD613 Consolidated Validation",
    "run_number": 1918,
    "run_id": 32539421026,
    "static_job_id": 96946346309,
    "static_job_conclusion": "success",
    "step_18_conclusion": "success",
    "full_repository": "skipped",
    "self_hosted": "skipped",
    "giving_practice_browser": "skipped",
    "front_line_browser": "skipped",
    "full_product_browser": "skipped"
  },
  "evidence_provenance": {
    "literal_e5_stdout_recovered": false,
    "bounded_log_recovery_attempted": true,
    "successful_exact_head_execution": true,
    "deterministic_exact_source_reconciliation": true,
    "green_workflow_used_as_survival_proof": false
  },
  "bounded_findings": {
    "e4_unadmitted_declared_edge_can_propagate": true,
    "e5_unadmitted_edge_refused": true,
    "materially_bound_live_admission_can_admit_edge": true,
    "stale_semantic_replacement_inherits_old_admission": false,
    "edge_identifier_is_authority": false,
    "admission_identifier_is_authority": false,
    "serialization_order_is_authority": false,
    "admission_multiplicity_is_confidence": false,
    "revoked_admission_retains_authority": false,
    "misbound_admission_authorizes_edge": false,
    "fabricated_copy_erases_valid_admission": false,
    "endpoint_snapshot_has_edge_admission_authority": false,
    "duplicate_admission_id_lexically_arbitrated": false,
    "sealed_admission_record_mutable": false,
    "e4_propagation_semantics_preserved_for_admitted_edge": true
  },
  "claim_ceiling": {
    "ledger_bound_edge_admission_is_admission_ledger_provenance": false,
    "ledger_bound_edge_admission_is_witnessed_authorization_event": false,
    "ledger_bound_edge_admission_is_institutional_authorization": false,
    "ledger_bound_edge_admission_is_real_world_authority": false
  },
  "next_learning_action": "ATTACK_EDGE_ADMISSION_LEDGER_PROVENANCE_AND_BOOTSTRAP_AUTHORITY_BEFORE_LARGER_GRAPH_COMPOSITION",
  "synthetic_exogenous_fixture": true,
  "live_external_source_adapter": false,
  "real_world_external_provenance_claim": false,
  "real_world_authorization_claim": false,
  "admission_ledger_provenance": "HELD_FOR_NEXT_ATTACK",
  "universal_graph_semantics": false,
  "scalar_aggregation_used": false,
  "H2": "HELD_NOT_TESTED_HERE",
  "H3": "HELD_NOT_TESTED_HERE",
  "intersections": "HELD_NOT_OPENED_HERE",
  "APERTURE_V32_REPLAY_STABILITY": "HELD_NOT_YET_WITNESSED",
  "promotion_authority": false,
  "product_mutation": false,
  "shared_pedagogue_engine_mutation": false,
  "workflow_mutation": false,
  "browser_execution": false,
  "merge_performed": false,
  "deployment_performed": false,
  "release_authority": false,
  "vercel_release_requires_issue_405_and_new_explicit_operator_gesture": true
}
