import assert from 'node:assert/strict';
import {executeRoute,endpointOnlyCompression,runCommutingTransitionRouteGauntlet} from '../app/dome-world/previews/a15-r0/aperture-pedagogue-commuting-transition-route-observability.js';
const A={id:'A',r:[1,0],x:[1,0],delta:[[0,0],[0,1]]};
const B={id:'B',r:[0,1],x:[0,1],delta:[[2,0],[0,0]]};
const T0=[[2,1],[1,3]];
const ab=executeRoute(T0,[A,B]);
const ba=executeRoute(T0,[B,A]);
assert.deepEqual(ab.transcript,[2,4]);
assert.equal(ab.aggregate,6);
assert.deepEqual(ba.transcript,[3,4]);
assert.equal(ba.aggregate,7);
assert.deepEqual(ab.final_operator,[[4,1],[1,4]]);
assert.deepEqual(ba.final_operator,ab.final_operator);
assert.deepEqual(endpointOnlyCompression(ab),endpointOnlyCompression(ba));
assert.equal(ab.custody[0].observation,2);
assert.deepEqual(ab.custody[0].operator_before,T0);
assert.deepEqual(ab.custody[0].operator_after,[[2,1],[1,4]]);
const r=runCommutingTransitionRouteGauntlet();
assert.equal(r.passed,true);
for(const [k,v] of Object.entries(r.criteria))assert.equal(v,true,`${k} must hold`);
assert.equal(r.transition_commutation.commute,true);
assert.equal(r.frozen_operator_control.AB.aggregate,5);
assert.equal(r.frozen_operator_control.BA.aggregate,5);
assert.equal(r.endpoint_only_custody.aliases_distinct_observation_histories,true);
assert.equal(r.canonical_bounded_scientific_claim,'TWO_PROGRAMS_USING_THE_SAME_ACTION_MULTISET_CAN_HAVE_COMMUTING_DECLARED_OPERATOR_TRANSITIONS_AND_THE_SAME_FINAL_OPERATOR_WHILE_PRODUCING_DIFFERENT_CUMULATIVE_OBSERVATION_TRANSCRIPTS_WHEN_MEASUREMENTS_ARE_SAMPLED_AT_DIFFERENT_INTERMEDIATE_OPERATOR_STATES_IN_THE_AUTHORED_FINITE_FIXTURE');
assert.equal(r.next_learning_action,'HELD_FOR_HUMAN_REVIEW_OF_PATH_OBJECT_AND_TRANSPORT_ONTOLOGY');
for(const k of ['path_category_earned','path_groupoid_earned','parallel_transport_earned','holonomy_earned','curvature_earned','canonical_operator_tomography_promotion_authority','physical_tomography_earned','berry_structure_earned','quantum_behavior_earned','proto_loom_earned','a16_reopened','merge_authority','production_authority','vercel_authority'])assert.equal(r[k],false,`${k} must remain false`);
console.log(JSON.stringify({schema:r.schema,AB:r.route_AB.transcript,BA:r.route_BA.transcript,same_endpoint:r.criteria.R3_same_endpoint,transitions_commute:r.transition_commutation.commute,claim:r.canonical_bounded_scientific_claim,next:r.next_learning_action}));