import assert from 'node:assert/strict';
import fs from 'node:fs';

const closeRepair = fs.readFileSync('app/dome-world/ash-case-close-repair.js', 'utf8');
const sessionBoundary = fs.readFileSync('app/dome-world/ash-session-boundary.js', 'utf8');
const bridge = fs.readFileSync('app/dome-world/ash-workspace-bridge.js', 'utf8');

assert.match(closeRepair, /td613\.ash\.case-close-repair\/v1\.7-case-list-quiescence/);
assert.match(closeRepair, /validThresholdReadiness/);
assert.match(closeRepair, /function clearAshSessionStorage\(\{ preserveReadiness = false \} = \{\}\)/);
assert.match(closeRepair, /if \(key === READINESS_KEY && keepReadiness\)/);
assert.match(closeRepair, /if \(!localStorage\.getItem\(POINTER_KEY\)\) exposeMembrane\(\{ preserveReadiness:true \}\);/);
assert.match(closeRepair, /async function saveAtCloseBoundary\(caseId, fingerprintPosture\)/);
assert.match(closeRepair, /async function awaitActiveSaveOperation\(caseId\)/);
assert.match(closeRepair, /await withOperation\(`save:\$\{caseId\}`, async \(\) => true\)/);
assert.match(closeRepair, /function caseListPosture\(expectedCaseId = ''\)/);
assert.match(closeRepair, /function waitForCaseListReady\(expectedCaseId = '', timeoutMs = 15000\)/);
assert.match(closeRepair, /attributeFilter:\['data-case-list-state','disabled'\]/);
assert.match(closeRepair, /const saveOperationSettled = await awaitActiveSaveOperation\(caseId\)/);
assert.match(closeRepair, /ashCloseSaveOperationSettled/);
assert.match(closeRepair, /const savePopulationSettled = await waitForCaseListReady\(\)/);
assert.match(closeRepair, /ashCloseSavePopulationSettled/);
assert.match(closeRepair, /PRE_CLOSE_BACKUP/);
assert.match(closeRepair, /POST_CLOSE_TRANSITION_SETTLED_BUNDLE/);
assert.match(closeRepair, /POST_CLOSE_RECONCILED_BUNDLE/);
assert.match(closeRepair, /const refreshCases = window\.__td613AshCaseControls\?\.refreshCases/);
assert.match(closeRepair, /if \(typeof refreshCases === 'function'\) await refreshCases\(expectedCaseId \|\| ''\)/);
assert.match(closeRepair, /let ready = await waitForCaseListReady\(expectedCaseId\)/);
assert.match(closeRepair, /if \(!ready && typeof refreshCases === 'function'\) \{[\s\S]*?await refreshCases\(expectedCaseId \|\| ''\)/);
assert.match(closeRepair, /Closed case did not reach the settled saved-case selector/);
assert.match(closeRepair, /ashCloseFingerprintPosture/);
assert.match(closeRepair, /ashCloseCaseListQuiescent/);
assert.match(closeRepair, /ashCloseCaseListPosture/);
const closeBody = closeRepair.match(/async function closeToMembrane\(\) \{[\s\S]*?\n\}/)?.[0] || '';
assert.match(closeBody, /exposeMembrane\(\);/);
assert.doesNotMatch(closeBody, /preserveReadiness:true/);
const releaseEpoch = '20260723-a2-a5-release-v1';
assert.match(bridge, new RegExp(`ash-case-close-repair\\.js\\?v=${releaseEpoch}`));
assert.match(bridge, new RegExp(`ash-session-boundary\\.js\\?v=${releaseEpoch}`));

assert.match(sessionBoundary, /v0\.4-pointer-governs-case-recovery-replay-stays-open/);
assert.match(sessionBoundary, /POINTER_KEY = 'td613\.ash-keep\.current-case'/);
assert.match(sessionBoundary, /if \(!activePointer\) return closedCurrent\(\)/);
assert.match(sessionBoundary, /case_id:null/);
assert.match(sessionBoundary, /function capsuleRecoveryOpen\(\)/);
assert.match(sessionBoundary, /workspace\?\.classList\.contains\('active'\)/);
assert.match(sessionBoundary, /Boolean\(file\?\.files\?\.length\)/);
assert.match(sessionBoundary, /visible\(returnBar\)/);
assert.match(sessionBoundary, /Boolean\(replay && !replay\.disabled && visible\(replay\)\)/);
assert.match(sessionBoundary, /const interactive = caseOpen \|\| recoveryOpen/);
assert.match(sessionBoundary, /if \(caseOpen\)[\s\S]*?rail\.removeAttribute\('inert'\)[\s\S]*?else[\s\S]*?rail\.setAttribute\('inert',''\)/);
assert.match(sessionBoundary, /attributeFilter:\['class','hidden','disabled'\]/);
assert.match(sessionBoundary, /RECOVERY_FILE_CHANGED/);
assert.match(sessionBoundary, /CUSTODIAN_RETURN_SETTLED/);
assert.match(sessionBoundary, /CAPSULE_OPENED_SETTLED/);
assert.match(sessionBoundary, /host\.__td613AshKeep = facade/);
assert.match(sessionBoundary, /td613:ash:case-closed/);
assert.match(sessionBoundary, /launch\?\.classList\.remove\('hidden'\)/);
assert.match(sessionBoundary, /main\.setAttribute\('inert',''\)/);
assert.doesNotMatch(sessionBoundary, /deleteDatabase|objectStore\([^)]*\)\.delete/);

console.log('ash-keep-ingress-readiness-close-boundary.test.mjs passed');
