import assert from 'node:assert/strict';
import fs from 'node:fs';
const read = path => fs.readFileSync(path, 'utf8');
const workflow = read('.github/workflows/ash-keep-production-closure.yml');
const probe = `${read('scripts/ash-lifecycle-production-probe.mjs')}\n${read('scripts/ash-lifecycle-production-probe-base.mjs')}`;
const convergenceRunner = read('scripts/run-ash-constitutional-convergence-probe.mjs');
const core = read('app/dome-world/ash-keep.js');
const controls = read('app/dome-world/ash-case-controls.js');
const keep = read('app/dome-world/ash-keep.html');
const delivery = read('app/dome-world/ash-keep-source.html');
const receipt = read('docs/ASH_LIFECYCLE_PRODUCTION_DEMO_RECEIPT.md');
const ledger = read('docs/ASH_KEEP_BUILDOUT_LEDGER.md');
const roadmap = read('ROADMAP.md');
const stretch11 = read('docs/ASH_KEEP_STRETCH11_CLOSURE_RECEIPT.md');
for (const marker of ['Ash Lifecycle Deployed Observation','Observe deployed Ash lifecycle without promotion','CONTINUITY_SEALED','promotion remains separate']) assert.ok(workflow.includes(marker));
for (const token of ['ARRIVAL_UNPERSISTED','CASE_BOUND','REBUILD_ELIGIBLE','RELEASE_ELIGIBLE','CONTINUITY_SEALED','promotion_authorized: false','continuity is not transport']) assert.ok(probe.includes(token));
for (const token of ['window.__td613AshKeep?.version','demo_click_deferred_until_ready: true','timeout: 60000']) assert.ok(convergenceRunner.includes(token));
assert.doesNotMatch(core, /location\.reload\(\)/);
assert.equal(delivery, keep);
assert.match(controls, /DELETE_PARTIAL_HOLD/);
assert.match(receipt, /Status: `EARNED`/);
assert.match(receipt, /lifecycle maturity promotion ≠ transport authorization/);
assert.match(ledger, /component maturity after Stretch 11 local closure = 358 \/ 375/);
assert.match(ledger, /Stretch 11 — CLOSED LOCALLY/);
assert.match(roadmap, /Stretch 11 · Destination-Bound Handoff — CLOSED LOCALLY/);
assert.match(stretch11, /new serverless function = false/);
assert.match(stretch11, /active serverless functions = 11/);
assert.match(stretch11, /transport capability = NAMED_SAME_ORIGIN_BROWSER_RECIPIENT_ONLY/);
console.log('ash-lifecycle-production-contract.test.mjs passed');
