import assert from 'node:assert/strict';
import {compileCapsuleImportReceipt,compileCapsuleRecall,compileCapsuleReturnReceipt,compileKeyTopology,compileKeyTopologyReceipt,compileMigrationDryRun,compileOriginManifest,decryptPortableCapsule,encryptPortableCapsule,signOriginManifest,verifyCapsuleDigest,verifyOriginSignature} from '../app/engine/ash-stretch12-r02-crypto.js';
const now=()=>new Date('2026-07-17T12:00:00.000Z');
const topology=await compileKeyTopology({case_id:'case_crypto',ciphertext_location_class:'LOCAL_ENCRYPTED_STORE',nodes:[{id:'dek',type:'data_key',location_class:'MEMORY',case_scope:'case_crypto',exportable:false},{id:'kek',type:'passphrase_derived_key',location_class:'MEMORY',case_scope:'case_crypto',exportable:false},{id:'ciphertext',type:'ciphertext',location_class:'LOCAL_ENCRYPTED_STORE',case_scope:'case_crypto'},{id:'recovery',type:'recovery_key',location_class:'OFFLINE_SEPARATE',case_scope:'case_crypto'}],edges:[{from:'kek',to:'dek',relation:'wraps'},{from:'dek',to:'ciphertext',relation:'authorizes'},{from:'recovery',to:'kek',relation:'recovers'}],created_at:now().toISOString()},{now});
assert.deepEqual(topology.dangerous_topology,[]);
assert.equal((await compileKeyTopologyReceipt(topology,{}, {now})).hold_state,'ELIGIBLE_FOR_CRYPTOGRAPHIC_PROCEDURE');
const records=[{record_id:'r1',record_class:'NOTE',body:'alpha'},{record_id:'r2',record_class:'MAP',body:'beta'}];
const passphrase='correct horse battery staple';
const capsule=await encryptPortableCapsule({case_id:'case_crypto',records,passphrase,key_topology:topology,origin_root:'sha256:origin',custody_root:'sha256:custody',database_version:'3',pbkdf2_iterations:600000,created_at:now().toISOString()},{now});
assert.equal(await verifyCapsuleDigest(capsule),true);
assert.equal(capsule.plaintext_persisted,false);
assert.equal(capsule.passphrase_persisted,false);
assert.equal(capsule.data_key_persisted,false);
assert.equal(new Set(capsule.records.map(item=>item.iv)).size,2);
assert.deepEqual(await decryptPortableCapsule(capsule,passphrase),records);
await assert.rejects(()=>decryptPortableCapsule(capsule,'incorrect passphrase'),/CAPSULE_OPEN_HELD/);
const tampered=structuredClone(capsule);tampered.records[0].ciphertext=tampered.records[0].ciphertext.slice(0,-4)+'AAAA';
await assert.rejects(()=>decryptPortableCapsule(tampered,passphrase),/digest|CAPSULE_IMPORT_HELD/);
const migration=await compileMigrationDryRun({case_id:'case_crypto',records,passphrase,key_topology:topology,origin_root:'sha256:origin',custody_root:'sha256:custody',database_version:'3',created_at:now().toISOString()},{now});
assert.equal(migration.status,'DRY_RUN_VERIFIED');assert.equal(migration.committed_to_live_store,false);
const importOk=await compileCapsuleImportReceipt(capsule,{expected_origin_root:'sha256:origin',expected_custody_root:'sha256:custody',created_at:now().toISOString()},{now});
assert.equal(importOk.status,'IMPORT_ELIGIBLE');
const stale=await compileCapsuleImportReceipt(capsule,{expected_origin_root:'sha256:new-origin',expected_custody_root:'sha256:custody',created_at:now().toISOString()},{now});
assert.ok(stale.holds.includes('STALE_ORIGIN_HOLD'));
const badTopology=await compileKeyTopology({case_id:'case_crypto',ciphertext_location_class:'CLOUD_ACCOUNT',nodes:[{id:'ciphertext',type:'ciphertext',location_class:'CLOUD_ACCOUNT'},{id:'recovery',type:'recovery_key',location_class:'CLOUD_ACCOUNT'}],edges:[{from:'ciphertext',to:'recovery',relation:'co-locates'}]},{now});
assert.ok(badTopology.dangerous_topology.some(item=>item.includes('RECOVERY_KEY')));
const manifest=await compileOriginManifest({case_id:'case_crypto',release_id:'release_1',exact_commit:'abc123',runtime_version:'node-24',dependency_lock_digest:'sha256:lock',assets:[{path:'a.txt',content:'alpha'},{path:'b.txt',content:'beta'}],created_at:now().toISOString()},{now});
const keys=await crypto.subtle.generateKey({name:'ECDSA',namedCurve:'P-256'},true,['sign','verify']);
const signature=await signOriginManifest(manifest,keys.privateKey);
assert.equal(await verifyOriginSignature(manifest,signature,keys.publicKey),true);
assert.equal(await verifyOriginSignature({...manifest,record_digest:'sha256:altered'},signature,keys.publicKey),false);
const returned=await compileCapsuleReturnReceipt({case_id:'case_crypto',release_reference:'release_1',return_object_digest:'sha256:return',created_at:now().toISOString()},{now});
assert.equal(returned.quarantine_state,'QUARANTINED');assert.equal(returned.automatic_case_merge,false);
const recall=await compileCapsuleRecall({case_id:'case_crypto',release_reference:'release_1',recall_scope:['recipient'],created_at:now().toISOString()},{now});
assert.equal(recall.external_deletion_verified,false);
console.log('ash-stretch12-r02-c.test.mjs passed');
