import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';

const PARENT_980_RECEIPT='3ac5778c601cdf6778c799e0ec46ba784e9b5e6b';
const PARENT_980_HARDENING_BLOB='0b76aa4f6069172c6e8f57700ae2e721a81984ec';
function resolveScientificHead(){const parents=execFileSync('git',['show','-s','--format=%P','HEAD'],{encoding:'utf8'}).trim().split(/\s+/).filter(Boolean);if(parents.length===2){const candidate=parents[1];try{execFileSync('git',['merge-base','--is-ancestor',PARENT_980_RECEIPT,candidate],{stdio:'pipe'});return candidate;}catch{}}return 'HEAD';}
const SCIENCE_HEAD=resolveScientificHead();execFileSync('git',['cat-file','-e',`${PARENT_980_RECEIPT}^{commit}`],{stdio:'pipe'});execFileSync('git',['merge-base','--is-ancestor',PARENT_980_RECEIPT,SCIENCE_HEAD],{stdio:'pipe'});const ahead=Number(execFileSync('git',['rev-list','--count',`${PARENT_980_RECEIPT}..${SCIENCE_HEAD}`],{encoding:'utf8'}).trim());assert.ok(ahead===7||ahead===8||ahead===9||ahead===10,'Atlas half-path orbit quotient chamber must be at hardened, frozen, or documented post-RED repair successor depth');
const changed=execFileSync('git',['diff','--name-only',`${PARENT_980_RECEIPT}..${SCIENCE_HEAD}`,'--','app/dome-world/docs/ash/experiments/a15-r0','app/dome-world/previews/a15-r0','tests'],{encoding:'utf8'}).trim().split('\n').filter(Boolean).filter(p=>p.startsWith('app/dome-world/docs/ash/experiments/a15-r0/')||p.startsWith('app/dome-world/previews/a15-r0/')||p.startsWith('tests/ash-a15-r0-'));
const freezePath='app/dome-world/docs/ash/experiments/a15-r0/ATLAS_SCHUBERT_PALINDROMIC_HALFPATH_ORBIT_FREEZE_V0_1.md';const allowed=new Set(['app/dome-world/docs/ash/experiments/a15-r0/ATLAS_SCHUBERT_PALINDROMIC_HALFPATH_ORBIT_PREREGISTRATION_V0_1.md','app/dome-world/docs/ash/experiments/a15-r0/ATLAS_SCHUBERT_PALINDROMIC_HALFPATH_ORBIT_EXPECTATIONS_V0_1.json','app/dome-world/docs/ash/experiments/a15-r0/ATLAS_SCHUBERT_PALINDROMIC_HALFPATH_ORBIT_BURDEN_V0_1.md',freezePath,'app/dome-world/previews/a15-r0/atlas-schubert-palindromic-halfpath-orbit.js','tests/ash-a15-r0-aperture-pedagogue-atlas-schubert-palindromic-halfpath-orbit.test.mjs','tests/ash-a15-r0-aperture-pedagogue-atlas-schubert-palindromic-halfpath-orbit-hostile.test.mjs','tests/ash-a15-r0-review-hardening.test.mjs']);const historicalMutations=changed.filter(p=>!allowed.has(p));assert.deepEqual(historicalMutations,[],`post-#980 orbit quotient chamber mutated inherited A15-R0 paths: ${historicalMutations.join(', ')}`);if(ahead===7){assert.equal(changed.includes(freezePath),false);assert.equal(changed.length,7);for(const p of allowed)if(p!==freezePath)assert.equal(changed.includes(p),true,`missing prefreeze orbit path: ${p}`);}else{assert.equal(changed.length,8);for(const p of allowed)assert.equal(changed.includes(p),true,`missing frozen orbit path: ${p}`);}if(ahead>=9)assert.equal(changed.length,allowed.size,'post-RED rank-coordinate repair must not widen the eight-path chamber surface');
const inheritedHardeningBlob=execFileSync('git',['rev-parse',`${PARENT_980_RECEIPT}:tests/ash-a15-r0-review-hardening.test.mjs`],{encoding:'utf8'}).trim();assert.equal(inheritedHardeningBlob,PARENT_980_HARDENING_BLOB,'earned #980 hardening blob changed or cannot be verified exactly');
await import('./ash-a15-r0-aperture-pedagogue-atlas-schubert-palindromic-halfpath-orbit.test.mjs');await import('./ash-a15-r0-aperture-pedagogue-atlas-schubert-palindromic-halfpath-orbit-hostile.test.mjs');console.log('Ash A15-R0 Atlas Schubert palindromic half-path orbit quotient hardening tests passed.');
