import assert from 'node:assert/strict';
import { holonomyLoomMossLanternDiscreteTransportCertificate } from '../app/dome-world/previews/a15-r0/holonomy-loom-moss-lantern-discrete-transport.js';

const cert=holonomyLoomMossLanternDiscreteTransportCertificate();
assert.equal(cert.passed,true);
assert.equal(cert.parent_exact,true);
assert.equal(cert.transport.group_size,8);
assert.equal(cert.transport.group_bijections,8);
assert.equal(cert.transport.group_inverse_failures,0);
assert.equal(cert.holonomy.basepoint_returns,4);
assert.equal(cert.holonomy.nonidentity_outputs,4);
assert.equal(cert.holonomy.unit_hamming_outputs,4);
assert.equal(cert.holonomy.marker_splits,4);
assert.equal(cert.holonomy.squared_identity_outputs,4);
assert.deepEqual(cert.holonomy.rows.map(row=>[row.start,row.end]),[['00','01'],['01','00'],['10','11'],['11','10']]);
assert.equal(cert.algebra.group_commutator_checks,64);
assert.equal(cert.algebra.distinct_commutator_values,2);
assert.equal(cert.algebra.commutator_subgroup_size,2);
assert.equal(cert.algebra.commutator_subgroup_exact_identity_plus_holonomy,true);
assert.equal(cert.controls.backtrack_checks,8);
assert.equal(cert.controls.backtrack_nonidentity_outputs,0);
assert.equal(cert.controls.commuting_control_checks,4);
assert.equal(cert.controls.commuting_control_nonidentity_outputs,0);
assert.equal(cert.controls.memoryless_endpoint_divergences,0);
assert.equal(cert.laws.formal_discrete_holonomy_nontrivial,true);
assert.equal(cert.laws.holonomy_order_two,true);
assert.equal(cert.laws.commutator_subgroup_exactly_identity_plus_holonomy,true);
assert.equal(cert.laws.backtrack_null,true);
assert.equal(cert.laws.commuting_square_null,true);
assert.equal(cert.laws.memoryless_endpoint_projection_blind,true);
assert.ok(cert.membranes.includes('FORMAL_DISCRETE_HOLONOMY != PHYSICAL_HOLONOMY'));
assert.ok(cert.membranes.includes('DECLARED_INVERSE_EDGE_TRANSPORT != OPERATIONAL_UNDO_OR_REVERSE_WORKFLOW'));
console.log('Ash A15-R0 Holonomy Loom / Moss Lantern discrete transport holonomy tests passed.');
