import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';

const PARENT_982_RECEIPT='3bb479aac6ce4791eec37cee8d1c438357dd860c';
const PARENT_982_HARDENING_BLOB='cd65fbe206f89f18fa3a7eba39328c2d25fa7119';
function resolveScientificHead(){const parents=execFileSync('git',['show','-s','--format=%P','HEAD'],{encoding:'utf8'}).trim().split(/\s+/).filter(Boolean);if(parents.length===2){const candidate=parents[1];try{execFileSync('git',['merge-base','--is-ancestor',PARENT_982_RECEIPT,candidate],{stdio:'pipe'});return candidate;}catch{}}return 'HEAD';}
const SCIENCE_HEAD=resolveScientificHead();execFileSync('git',['cat-file','-e',`${PARENT_982_RECEIPT}^{commit}`],{stdio:'pipe'});execFileSync('git',['merge-base','--is-ancestor',PARENT_982_RECEIPT,SCIENCE_HEAD],{stdio:'pipe'});const ahead=Number(execFileSync('git',['rev-list','--count',`${PARENT_982_RECEIPT}..${SCIENCE_HEAD}`],{encoding:'utf8'}).trim());assert.ok(ahead===1,'Atlas relation-identity custody chamber must be one atomic frozen science commit above earned #982');
const changed=execFileSync('git',['diff','--name-only',`${PARENT_982_RECEIPT}..${SCIENCE_HEAD}`,'--','app/dome-world/docs/ash/experiments/a15-r0','app/dome-world/previews/a15-r0','tests'],{encoding:'utf8'}).trim().split('\n').filter(Boolean).filter(p=>p.startsWith('app/dome-world/docs/ash/experiments/a15-r0/')||p.startsWith('app/dome-world/previews/a15-r0/')||p.startsWith('tests/ash-a15-r0-'));
const allowed=new Set(['app/dome-world/docs/ash/experiments/a15-r0/ATLAS_RELATION_IDENTITY_CUSTODY_PREREGISTRATION_V0_1.md','app/dome-world/docs/ash/experiments/a15-r0/ATLAS_RELATION_IDENTITY_CUSTODY_EXPECTATIONS_V0_1.json','app/dome-world/docs/ash/experiments/a15-r0/ATLAS_RELATION_IDENTITY_CUSTODY_BURDEN_V0_1.md','app/dome-world/docs/ash/experiments/a15-r0/ATLAS_RELATION_IDENTITY_CUSTODY_FREEZE_V0_1.md','app/dome-world/previews/a15-r0/atlas-relation-identity-custody.js','tests/ash-a15-r0-aperture-pedagogue-atlas-relation-identity-custody.test.mjs','tests/ash-a15-r0-aperture-pedagogue-atlas-relation-identity-custody-hostile.test.mjs','tests/ash-a15-r0-review-hardening.test.mjs']);assert.equal(changed.length,8);for(const p of allowed)assert.equal(changed.includes(p),true,`missing frozen relation-identity custody path: ${p}`);assert.deepEqual(changed.filter(p=>!allowed.has(p)),[]);
const inherited=execFileSync('git',['rev-parse',`${PARENT_982_RECEIPT}:tests/ash-a15-r0-review-hardening.test.mjs`],{encoding:'utf8'}).trim();assert.equal(inherited,PARENT_982_HARDENING_BLOB,'earned #982 hardening blob changed or cannot be verified exactly');
await import('./ash-a15-r0-aperture-pedagogue-atlas-relation-identity-custody.test.mjs');await import('./ash-a15-r0-aperture-pedagogue-atlas-relation-identity-custody-hostile.test.mjs');console.log('Ash A15-R0 Atlas relation-identity custody hardening tests passed.');
