import assert from 'node:assert/strict';
import {
  gT,
  gE,
  gO,
  gS,
  kernelElement,
  kernelCoordinates,
  tauK,
  normK,
  parityExtensionCertificate,
  extensionCohomologyCertificate,
  oddLiftSquareCertificate,
  torsionFreeCertificate,
  affineOf,
  composeAffine,
  applyAffine,
  affineRepresentationCertificate,
  freeCrystallographicActionCertificate,
  flatManifoldInstantiationCertificate,
  malformedNoHalfTranslationCertificate,
  nonsplitBieberbachAffineFlat3ManifoldCertificate,
} from '../app/dome-world/previews/a15-r0/aperture-pedagogue-nonsplit-bieberbach-affine-flat-3-manifold.js';
import {
  integerFractionGroupMultiply,
  integerFractionGroupInverse,
} from '../app/dome-world/previews/a15-r0/aperture-pedagogue-exact-bar-h2-torsion-sensitive-holonomy.js';

const PARENT_RECEIPT='39b8f6e8ba319154378d03c28a1bf42c02870de1';

const ext0=parityExtensionCertificate();
assert.equal(ext0.passed,true);
assert.equal(ext0.parent_receipt,PARENT_RECEIPT);
assert.deepEqual(ext0.T_squared,gS());
assert.deepEqual(ext0.conjugation.e,gO());
assert.deepEqual(ext0.conjugation.o,gE());
assert.deepEqual(ext0.conjugation.s,gS());

// Independently recompute K^tau / N(K) from the three K-basis generators.
const kE={a:1,b:0,c:0};
const kO={a:0,b:1,c:0};
const kS={a:0,b:0,c:1};
assert.deepEqual(tauK(kE),kO);
assert.deepEqual(tauK(kO),kE);
assert.deepEqual(tauK(kS),kS);
assert.deepEqual(normK(kE),{a:1,b:1,c:0});
assert.deepEqual(normK(kO),{a:1,b:1,c:0});
assert.deepEqual(normK(kS),{a:0,b:0,c:2});

// Coordinates in invariant basis u=e+o, s: (m,m,n) -> (m,n).
const normInvariantColumns=[
  [normK(kE).a,normK(kE).c],
  [normK(kO).a,normK(kO).c],
  [normK(kS).a,normK(kS).c],
];
const minors=[];
for(let i=0;i<normInvariantColumns.length;i++){
  for(let j=i+1;j<normInvariantColumns.length;j++){
    const a=normInvariantColumns[i], b=normInvariantColumns[j];
    minors.push(Math.abs(a[0]*b[1]-a[1]*b[0]));
  }
}
const gcd=(a,b)=>{let x=Math.abs(a),y=Math.abs(b);while(y!==0)[x,y]=[y,x%y];return x;};
const index=minors.reduce((d,m)=>gcd(d,m),0);
assert.equal(index,2,'norm image must have index two in the invariant lattice');

const ext=extensionCohomologyCertificate();
assert.equal(ext.passed,true);
assert.equal(ext.quotient,'Z/2 generated by [s]');
assert.equal(ext.alpha_class,'nonzero generator [s]');
assert.equal(ext.split,false);

// Hostile: s cannot be a norm because every norm has even s-coordinate.
for(let a=-5;a<=5;a++) for(let b=-5;b<=5;b++) for(let c=-5;c<=5;c++) {
  assert.notDeepEqual(normK({a,b,c}),{a:0,b:0,c:1});
}

const lifts=oddLiftSquareCertificate();
assert.equal(lifts.passed,true);
assert.equal(lifts.no_order_two_odd_lift,true);
assert.equal(lifts.section_independent_nonsplitting,true);
assert.equal(lifts.rows.every((r)=>Math.abs(r.square.c%2)===1),true);

// Independent square formula on a wider grid.
for(let a=-4;a<=4;a++) for(let b=-4;b<=4;b++) for(let c=-4;c<=4;c++) {
  const k=kernelElement({a,b,c});
  const kT=integerFractionGroupMultiply(k,gT());
  const sq=kernelCoordinates(integerFractionGroupMultiply(kT,kT));
  assert.deepEqual(sq,{a:a+b,b:a+b,c:2*c+1});
  assert.notDeepEqual(sq,{a:0,b:0,c:0});
}

const torsion=torsionFreeCertificate();
assert.equal(torsion.passed,true);
assert.equal(torsion.kernel_torsion_free,true);
assert.equal(torsion.odd_coset_square_never_identity,true);

const rho=affineRepresentationCertificate();
assert.equal(rho.passed,true);
assert.equal(rho.faithful,true);
assert.equal(rho.euclidean_isometries,true);
assert.equal(rho.determinant,-1);
assert.equal(rho.homomorphism_rows_pass,true);
assert.equal(rho.faithfulness_rows_pass,true);

// Exact glide and square.
const Taff=affineOf(gT());
assert.deepEqual(applyAffine(Taff,[2,3,5]),[3,2,5.5]);
assert.deepEqual(composeAffine(Taff,Taff),affineOf(gS()));

// Exact conjugation in the affine representation.
const invT=affineOf(integerFractionGroupInverse(gT()));
const conj=(x)=>composeAffine(composeAffine(Taff,affineOf(x)),invT);
assert.deepEqual(conj(gE()),affineOf(gO()));
assert.deepEqual(conj(gO()),affineOf(gE()));
assert.deepEqual(conj(gS()),affineOf(gS()));

const action=freeCrystallographicActionCertificate();
assert.equal(action.passed,true);
assert.equal(action.translation_lattice_rank,3);
assert.equal(action.translation_lattice_determinant,1);
assert.equal(action.translation_subgroup_index,2);
assert.equal(action.discrete,true);
assert.equal(action.cocompact,true);
assert.equal(action.free,true);
assert.equal(action.properly_discontinuous,true);
assert.equal(action.odd_rows.every((r)=>r.half_integer&&r.fixed_point_impossible),true);

const manifold=flatManifoldInstantiationCertificate();
assert.equal(manifold.passed,true);
assert.equal(manifold.group,'G is a 3-dimensional Bieberbach group');
assert.equal(manifold.manifold,'M=R^3/rho(G) is a connected closed flat Riemannian 3-manifold');
assert.equal(manifold.fundamental_group,'pi_1(M) ≅ G');
assert.equal(manifold.universal_cover,'R^3');
assert.equal(manifold.aspherical,true);
assert.equal(manifold.linear_holonomy,'C2 generated by A');
assert.equal(manifold.orientable,false);
assert.equal(manifold.orientation_double_cover,'R^3/rho(K)=T^3');
assert.equal(manifold.classification_name,'UNCLAIMED');
assert.equal(manifold.geometric_model_authority,true);
assert.equal(manifold.physical_spacetime_authority,false);
assert.equal(manifold.operational_route_geometry_authority,false);
assert.equal(manifold.geometric_two_holonomy_authority,false);
assert.equal(manifold.berry_or_gerbe_holonomy_authority,false);

// Hostile: deleting the half-translation makes T order two and creates fixed points.
const malformed=malformedNoHalfTranslationCertificate();
assert.equal(malformed.passed,true);
assert.equal(malformed.bad_square_is_identity,true);
assert.equal(malformed.bad_generator_fixes_witness,true);

const all=nonsplitBieberbachAffineFlat3ManifoldCertificate();
assert.equal(all.passed,true);
assert.equal(all.hard_ceilings.physical_spacetime,false);
assert.equal(all.hard_ceilings.td613_curvature,false);
assert.equal(all.hard_ceilings.geometric_two_holonomy,false);
assert.equal(all.hard_ceilings.berry_gerbe_holonomy,false);
assert.equal(all.hard_ceilings.operational_route_group,false);
assert.equal(all.hard_ceilings.ontology,false);
assert.equal(all.candidate_classifications.includes('NONSPLIT_BIEBERBACH_AFFINE_FLAT_THREE_MANIFOLD_INSTANTIATION_EARNED'),true);

console.log('Ash A15-R0 nonsplit Bieberbach affine flat 3-manifold tests passed.');
