import assert from 'assert';
import { execFileSync } from 'child_process';
import fs from 'fs';

execFileSync('node', ['scripts/patch-td613-flight-mobile.mjs'], { stdio: 'inherit' });
const html = fs.readFileSync('app/safe-harbor/td613-flight.html', 'utf8');

assert(html.includes('Seal payload to begin Flight'));
assert(html.indexOf('mobile-prompt-rail') < html.indexOf('devSettingsDrawer'));
assert(html.includes('>Copy</button>'));
assert(html.includes('>Clear</button>'));
assert(!html.includes('Copy from output'));
assert(!html.includes('Clear output'));
assert(html.includes('14dvh'));
assert(html.includes('max-height: 16dvh'));
assert(!html.includes('Loading TD613 Flight'));
assert(!html.includes('td613-flight-legacy.html'));
assert(!html.includes('<iframe'));
assert(html.includes('TD613 Flight direct mobile layout fix'));
assert(html.includes('TD613 Flight mobile lane access override'));
assert(html.includes('TD613 Flight PR73 mobile finale'));
assert(html.includes('TD613 Flight PR76 native mobile lane repair'));
assert(html.includes('-webkit-text-size-adjust: 100% !important'));
assert(html.includes('min-width: 0 !important'));
assert(html.includes('maximum-scale=1'));
assert(html.includes('user-scalable=no'));
assert(html.includes('flight-output-active'));
assert(html.includes('mobileSwipeOverlay'));
assert(html.includes('mobile-swipe-overlay'));
assert(!html.includes('mobile-swipe-cue'));
assert(!html.includes('Swipe right'));
assert(html.includes('⟵⟵ swipe'));
assert(html.includes('Orbitron, Eurostile, Audiowide'));
assert(html.includes('pointer-events: none !important'));
assert(html.includes('mobileSwipeOverlayExit'));
assert(html.includes('sealedOutputBlinkStrong .82s ease-in-out 5'));
assert(html.includes('touchstart'));
assert(html.includes('touchmove'));
assert(html.includes('touchend'));
assert(html.includes('overflow-x: auto !important'));
assert(html.includes('scroll-snap-type: x mandatory !important'));
assert(html.includes('scrollTo({ left: target ==='));
assert(html.includes('transform: none !important'));
assert(html.includes('td613-flight-pr76-native-mobile-lane-script'));
assert(!html.includes('td613-flight-pr71-mobile-polish-script'));
assert(!html.includes('td613-flight-pr74-mobile-lane-rescue-script'));
assert(!html.includes('td613-flight-pr75-mobile-lane-recovery-script'));
assert(!html.includes('grid.scrollIntoView'));
assert(html.includes('function syncTabs(target)'));
assert(html.includes('function currentFromScroll()'));
assert(html.includes('textarea, input, select'));
assert(html.includes('TD613FlightSetLane'));
assert(html.includes('zoom: .68 !important'));
assert(html.includes('font-size: 16px !important'));
assert(html.includes('min-height: .98rem !important'));
assert(html.includes('font-size: .31rem !important'));
assert(html.includes('input[type="checkbox"]'));
assert(html.includes('input[type="radio"]'));
assert(html.includes('width: .46rem !important'));
assert(html.includes('justify-content: flex-start !important'));
assert(html.includes('gesturestart'));
assert(html.includes('dblclick'));
console.log('td613-flight-mobile-layout tests passed');