import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {loadFoundationalTargets} from '../packages/dome_world_exact/fixtures/a15-r0/WENDBINE/99-ADMIN/wendbine-reddit-oauth-rescue.mjs';
import {PROVIDERS,providerUrl,parseArchiveEnvelope,assessArchiveObject,probeP0Archives}
 from '../packages/dome_world_exact/fixtures/a15-r0/WENDBINE/99-ADMIN/wendbine-archive-provider-probe.mjs';
const roster=loadFoundationalTargets();
assert.equal(roster.length,33);
assert.ok(providerUrl(PROVIDERS[0],roster).includes('/api/posts/ids?ids='));
assert.ok(providerUrl(PROVIDERS[1],roster).includes('/reddit/search/submission/?ids='));
const target=roster[0], id=target.source_id.slice('reddit:t3_'.length);
const created=Date.parse(target.publication_day_as_catalogued+'T12:00:00Z')/1000;
const item={id,author:'Upset-Ratio502',subreddit:'Wendbine',title:'Source title ⟐',selftext:'Exact  \r\n  original ∴ body',created_utc:created,retrieved_on:1789040000};
assert.equal(assessArchiveObject(item,target,PROVIDERS[0]).state,'ARCHIVED_TEXT_FIELDS_FOUND_LIVE_STATE_UNVERIFIED');
assert.equal(assessArchiveObject({...item,author:'other'},target,PROVIDERS[0]).state,'AUTHOR_MISMATCH');
assert.equal(assessArchiveObject({...item,selftext:'[deleted]'},target,PROVIDERS[0]).state,'DELETED_OR_REMOVED_BODY_NOT_ADMITTED');
assert.equal(assessArchiveObject({...item,created_utc:Date.parse('2020-01-01')/1000},target,PROVIDERS[0]).state,'CATALOGUED_DAY_CONFLICT');
assert.equal(parseArchiveEnvelope(Buffer.from(JSON.stringify([item])),PROVIDERS[0]).length,1);
assert.equal(parseArchiveEnvelope(Buffer.from(JSON.stringify({data:[item]})),PROVIDERS[1]).length,1);
assert.throws(()=>parseArchiveEnvelope(Buffer.from('{"message":"blocked"}'),PROVIDERS[0]),/UNRECOGNIZED_RESPONSE_SHAPE/);
const raw0=Buffer.from(JSON.stringify([item]));
const raw1=Buffer.from(JSON.stringify({data:[{...item,title:'Different archive snapshot'}]}));
const fetchImpl=async url=>({ok:true,status:200,arrayBuffer:async()=>url.includes('arctic-shift')?raw0:raw1});
const report=await probeP0Archives({fetchImpl,targets:roster});
assert.equal(report.target_count,33);
assert.equal(report.matched_source_ids,1);
assert.equal(report.missing_source_ids,32);
assert.equal(report.source_versions_conflicting,1,'Never silently collapse competing archival versions.');
assert.equal(report.providers.length,2);
assert.equal(report.records[0].provider_copies.length,2);
assert.equal(report.records[0].original_publication_version_verified,false);
assert.equal(report.records[0].live_deletion_state_verified,false);
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'wendbine-archives-'));
try{
 const privateDir=path.join(tmp,'private-archive');
 await assert.rejects(()=>probeP0Archives({fetchImpl,targets:roster,saveRaw:true,destination:privateDir}),/EXPLICIT_RIGHTS_BASIS_REQUIRED/);
 const saved=await probeP0Archives({fetchImpl,targets:roster,saveRaw:true,destination:privateDir,rightsBasis:'AUTHOR_PERMISSION'});
 assert.equal(saved.matched_source_ids,1);
 assert.ok(fs.readFileSync(path.join(privateDir,'raw-arctic_shift.json')).equals(raw0));
 assert.ok(fs.readFileSync(path.join(privateDir,'raw-pullpush.json')).equals(raw1));
 const stored=JSON.parse(fs.readFileSync(path.join(privateDir,'coverage-report.json')));
 assert.equal(stored.records[0].provider_copies.length,2);
 assert.ok(!JSON.stringify(report).includes(item.selftext),'Public coverage report must not repeat full source text.');
 assert.equal(fs.statSync(path.join(privateDir,'raw-arctic_shift.json')).mode&0o777,0o600);
 await assert.rejects(()=>probeP0Archives({fetchImpl,targets:roster,saveRaw:true,destination:privateDir,rightsBasis:'AUTHOR_PERMISSION'}),/REFUSE_OVERWRITE_PRIVATE_ARCHIVE/);
 const denied=await probeP0Archives({targets:roster,fetchImpl:async()=>({status:403,ok:false})});
 assert.equal(denied.matched_source_ids,0);
 assert.equal(denied.providers.length,2);
 assert.ok(denied.providers.every(p=>p.state==='PROVIDER_UNAVAILABLE_OR_UNRECOGNIZED'&&p.http_status===403));
}finally{fs.rmSync(tmp,{recursive:true,force:true});}
console.log('Wendbine Arctic Shift and PullPush source-ID probe: 33 targets, provider version conflicts, private capture and held-state tests passed.');
