import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { buildIndex, lexicalSearch, semanticSearch, resolveEntry, recentEntries } from '../packages/dome_world_exact/fixtures/a15-r0/WENDBINE/99-ADMIN/wendbine-query.mjs';
import { validateCaptureReconciliation } from '../packages/dome_world_exact/fixtures/a15-r0/WENDBINE/99-ADMIN/wendbine-capture-contract.mjs';

const root = path.resolve('packages/dome_world_exact/fixtures/a15-r0/WENDBINE');
const registryPath = path.join(root, '01-MANIFESTS/public-reddit-account-card-source-registry-20260922-v05.jsonl');
const snapshot = JSON.parse(fs.readFileSync(path.join(root, '01-MANIFESTS/public-reddit-account-card-sync-20260922-v05.json'), 'utf8'));
const receipt = JSON.parse(fs.readFileSync(path.join(root, '04-RECEIPTS/2026-09-22-public-account-card-capture-reconciliation-v05.json'), 'utf8'));
const media = JSON.parse(fs.readFileSync(path.join(root, '04-RECEIPTS/2026-09-22-linked-audiovisual-discovery-v01.json'), 'utf8'));
const records = fs.readFileSync(registryPath, 'utf8').split(/\r?\n/).filter(Boolean).map(line => JSON.parse(line));
assert.equal(records.length, 25, 'Every captured account card must be an individual JSONL record.');
assert.equal(new Set(records.map(r => r.source_id)).size, 25, 'Source IDs must be unique.');
assert.equal(new Set(records.map(r => r.canonical_url)).size, 25, 'Canonical URLs must be unique.');
assert.deepEqual(records.map(r => r.listing_position), Array.from({length:25}, (_, i) => i+1), 'Preserve the visible listing order without promoting it to exact publication chronology.');
assert.equal(records.filter(r => r.media_card).length, 2, 'Media-only cards must survive as card observations.');
for (const r of records) {
  assert.equal(r.public_account_handle, 'u/Upset-Ratio502', 'Reject unrelated public authors from this account-scoped sync.');
  assert.equal(r.account_binding_basis, 'RENDERED_R_WENDBINE_NEW_CARD_AUTHOR_AND_LINK');
  assert.match(r.source_id, /^reddit:t3_[a-z0-9]+$/);
  assert.ok(r.canonical_url.includes(r.source_id.slice(10)), 'Source ID must resolve to the individual post URL.');
  assert.equal(r.post_detail_retrieved, false, 'Cache-missing post detail must never be silently promoted.');
  assert.equal(r.public_date, null, 'Retrieval day must not be relabeled post publication day.');
  assert.equal(r.time_precision, 'PUBLICATION_UNBOUND_OBSERVATION_DAY_ONLY');
  assert.equal(r.retrieval_day_utc, '2026-09-22');
  assert.equal(r.source_text_stored, false);
  assert.equal(r.technical_header_status, 'ARCHIVE_EDITORIAL_DESCRIPTOR_NOT_SOURCE_TITLE');
  assert.equal(r.concept_status, 'ARCHIVE_NORMALIZED_NOT_SOURCE_DECLARATION');
  if (r.media_card) assert.equal(r.normalized_summary, null, 'Never invent media-only card content.');
  else assert.ok(r.normalized_summary?.length > 12, 'Every text-bearing card needs a bounded recoverable summary.');
}
assert.equal(snapshot.coverage.observed_account_cards, records.length);
assert.equal(snapshot.coverage.persisted_per_card_records, records.length);
assert.equal(snapshot.coverage.text_discussion_cards + snapshot.coverage.media_only_cards, records.length);
assert.equal(receipt.persisted.individual_card_rows, records.length);
assert.equal(receipt.persisted.unique_source_ids, records.length);
assert.equal(receipt.persisted.unique_canonical_urls, records.length);
assert.equal(validateCaptureReconciliation({ observedCount:25, persistedCount:25, explicitFailureCount:0 }).state, 'RECONCILED_FULL_PER_CARD_CUSTODY');
assert.throws(() => validateCaptureReconciliation({ observedCount:25, persistedCount:24, explicitFailureCount:0 }), /FAILED_CAPTURE_RECONCILIATION/);
assert.equal(snapshot.prior_state.fully_hydrated_public_reddit_post_count, 35, 'Card-level sync must not silently rewrite the older fully hydrated source count.');
assert.equal(snapshot.prior_state.this_snapshot_updates_sept16_per_card_identity, false);
assert.equal(media.verified_video_count, 0, 'No video may be admitted without a public account linkage.');
assert.equal(media.verified_channel_url, null);
assert.equal(media.reported_quote_search.verified_exact_quote, false);
const index = buildIndex(root);
const sourceId = 'reddit:t3_1wkx9ed';
const hit = resolveEntry(index, sourceId);
assert.equal(hit.length, 1, 'Stable-ID resolution must find the new record.');
assert.equal(hit[0].date_basis, 'RETRIEVAL_DAY', 'Observed-on date must carry its basis.');
assert.equal(hit[0].time_precision, 'PUBLICATION_UNBOUND_OBSERVATION_DAY_ONLY');
assert.ok(lexicalSearch(index, 'Hooptea playlist', {limit:40}).some(r => r.id === sourceId), 'Lexical search should recover new individual card by terms.');
assert.ok(semanticSearch(index, 'due diligence reconciliation', {limit:30}).some(r => r.id === 'reddit:t3_1wkn1a3'), 'Concept retrieval should reach the new card without filename knowledge.');
assert.ok(semanticSearch(index, 'TARDIS phone visual', {limit:30}).some(r => r.id === 'reddit:t3_1wkvgzv'), 'Visual content description should be recoverable.');
const recent = recentEntries(index, {limit:60, sourceOnly:true});
assert.ok(recent.some(r => r.id === sourceId && r.date_basis === 'RETRIEVAL_DAY'), 'Source chronology must retain observation/publication distinction.');
console.log('Wendbine September 22 individual account-card archive, custody and query regression passed.');
