import { extractCadenceProfile } from './engine/stylometry.js';
import { buildEscapeVector } from './engine/escape-vector.js';
import { buildIngestionFrictionAudit } from './engine/ingestion-friction.js';
import { buildEscapeControllerDecision } from './engine/escape-controller.js';
import { appendAcceptedOutput, createPersonaMemory, derivePersonaField, summarizePersonaMemory } from './engine/persona-memory.js';
import { appendIterationRow, createIterationLedger, exportIterationLedgerJson, linkAcceptedOutputToIteration, summarizeIterationLedger } from './engine/iteration-ledger.js';
import { evaluateClaimCeiling } from './engine/claim-ladder.js';
import { buildReportPayload, exportReportJson, exportReportMarkdown } from './engine/report-export.js';
import { CONTEXT_TYPES, buildContextProfile } from './engine/context-profile.js';
import { buildRecognitionField } from './engine/recognition-field.js';
import { listHushMasks, getHushMask, buildHushMaskProfile, summarizeHushMask, exportHushMaskJson } from './engine/hush-mask-studio.js';
import { createCustomMask, addCustomMaskSample, rebuildCustomMaskProfile, summarizeCustomMask, exportCustomMaskJson } from './engine/hush-custom-mask.js';
import { buildProfileMatch, summarizeProfileMatch } from './engine/hush-profile-match.js';
import { buildHushSwap, exportHushSwapJson } from './engine/hush-swap.js';

const DEFAULT_MODE = 'neutralize';
const CANONICAL_TOKENS = Object.freeze({ khonaLitPo: 'Khona\u200Clit-po', glyphs: ['𝌋', '⟐'], badgeStrings: [] });
const STATE_LABELS = Object.freeze({ continue: 'Continue steering', hold: 'Hold for review', rotate: 'Rotate mask', restore: 'Restore semantics', seal: 'Locally sealable' });
const fmt = (value) => Number.isFinite(value) ? value.toFixed(2) : 'unavailable';
const safeText = (value) => String(value ?? '');
const initialProfiles = () => ({ protectedBaseline: null, maskReference: null, messageDraft: null, protectedOutput: null });
const asArray = (value) => Array.isArray(value) ? [...value] : [];

export const benchState = {
  protectedBaselineText: '',
  maskReferenceText: '',
  messageDraftText: '',
  protectedOutputText: '',
  selectedPersonaId: '',
  selectedHushMaskId: '',
  hushMasks: [],
  selectedHushMask: null,
  customMasks: [],
  activeCustomMask: null,
  hushProfileMatch: null,
  hushSwapResult: null,
  hushMode: 'built-in',
  recognitionContextType: 'group-chat',
  recognitionIntentMode: 'neutralize',
  recognitionExposureDuration: 'single-use',
  contextProfile: null,
  recognitionField: null,
  personaMemory: null,
  profiles: initialProfiles(),
  ingestionAudit: null,
  escapeVector: null,
  controllerDecision: null,
  claimCeiling: null,
  reportPayload: null,
  iterationPreview: [],
  iterationTextCache: {},
  iterationLedger: createIterationLedger({ context: { benchVersion: 'phase-11', product: 'TD613 Hush', mode: DEFAULT_MODE } })
};

let docRef = null;
let initializedFor = null;
const $ = (id) => docRef?.getElementById(id) || null;
const setText = (id, value) => { const el = $(id); if (el) el.textContent = safeText(value); };
const setHtml = (id, value) => { const el = $(id); if (el) el.innerHTML = safeText(value); };
function escapeHtml(value = '') { return safeText(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&#39;'); }
function profileSummary(profile) { if (!profile || profile.empty) return 'No profile yet.'; const parts = []; if (Number.isFinite(profile.wordCount)) parts.push(`Words ${profile.wordCount}`); if (Number.isFinite(profile.avgSentenceLength)) parts.push(`Rhythm ${profile.avgSentenceLength.toFixed(1)}w`); if (Number.isFinite(profile.punctuationDensity)) parts.push(`Punct ${profile.punctuationDensity.toFixed(2)}`); if (Number.isFinite(profile.contractionDensity)) parts.push(`Contractions ${profile.contractionDensity.toFixed(2)}`); if (Number.isFinite(profile.recurrencePressure)) parts.push(`Recurrence ${profile.recurrencePressure.toFixed(2)}`); return parts.length ? parts.join(' · ') : 'Profile extracted.'; }
function selectedMask() { return benchState.selectedHushMask || getHushMask(benchState.selectedHushMaskId, { masks: benchState.hushMasks }) || benchState.hushMasks[0] || null; }
function selectedPersona() { return selectedMask(); }
function createMemoryForMask(mask) { return createPersonaMemory({ personaId: mask?.id || 'hush-mask-field', label: mask?.label || 'Hush Mask Field', displayName: mask?.label || 'Hush Mask Field', surface: { avatar: '', description: mask?.description || '', tags: [mask?.family, mask?.intendedUse].filter(Boolean) }, ontology: { role: mask?.family || 'mask field', targetContexts: ['protected communication'], registerHints: Object.values(mask?.transformHints || {}).filter(Boolean), belongingNotes: mask?.intendedUse ? [mask.intendedUse] : [] }, ritualSurface: { optionalMarkers: ['𝌋', '⟐'], glyphs: ['𝌋', '⟐'] } }); }
function createMemoryForPersona(persona) { return createMemoryForMask(persona); }
function ensurePersonaMemory() { const mask = selectedMask(); if (!benchState.personaMemory || benchState.personaMemory.personaId !== (mask?.id || 'hush-mask-field')) benchState.personaMemory = createMemoryForMask(mask); return benchState.personaMemory; }
function activePersonaField() { const memory = ensurePersonaMemory(); const field = derivePersonaField(memory); const mask = selectedMask(); if (field.maskProfile) return field; if (benchState.maskReferenceText.trim()) return { ...field, maskProfile: benchState.profiles.maskReference, maskHistory: [{ text: benchState.maskReferenceText, profile: benchState.profiles.maskReference }] }; if (mask?.profile) return { ...field, personaId: mask.id, label: mask.label, maskProfile: mask.profile, maskHistory: [{ text: mask.sampleSeed || `${mask.label}. ${mask.description || ''}`, profile: mask.profile }] }; return field; }
function readInputs() { benchState.protectedBaselineText = $('protectedBaselineInput')?.value || ''; benchState.maskReferenceText = $('maskReferenceInput')?.value || ''; benchState.messageDraftText = $('messageDraftInput')?.value || ''; benchState.protectedOutputText = $('protectedOutputInput')?.value || ''; benchState.selectedHushMaskId = $('maskFieldSelect')?.value || benchState.selectedHushMaskId; benchState.selectedPersonaId = benchState.selectedHushMaskId; benchState.recognitionContextType = $('recognitionContextType')?.value || benchState.recognitionContextType; benchState.recognitionIntentMode = $('recognitionIntentMode')?.value || benchState.recognitionIntentMode; benchState.recognitionExposureDuration = $('recognitionExposureDuration')?.value || benchState.recognitionExposureDuration; }
function extractProfiles() { benchState.profiles.protectedBaseline = extractCadenceProfile(benchState.protectedBaselineText); benchState.profiles.maskReference = extractCadenceProfile(benchState.maskReferenceText); benchState.profiles.messageDraft = extractCadenceProfile(benchState.messageDraftText); benchState.profiles.protectedOutput = extractCadenceProfile(benchState.protectedOutputText); }
function extractProtectedLiterals() { const text = `${benchState.messageDraftText}\n${benchState.protectedBaselineText}`; return [...new Set([...(text.match(/\b(?:EXHIBIT|DOC|CASE|ID|REF|TD613|SHI|SAC)[A-Z0-9:_#\/-]*\b/g) || []), ...(text.match(/\b\d{2,}(?:[\-/:.]\d+)*\b/g) || [])])].slice(0, 24); }
function metricRow(label, value) { return `<div class="hush-metric-row"><span>${escapeHtml(label)}</span><strong>${escapeHtml(value)}</strong></div>`; }
function renderProfiles() { setText('protectedBaselineProfile', profileSummary(benchState.profiles.protectedBaseline)); setText('maskFieldProfile', profileSummary(activePersonaField().maskProfile || benchState.profiles.maskReference)); setText('messageDraftProfile', profileSummary(benchState.profiles.messageDraft)); renderHushMaskProfile(); }
function metricCard(label, value) { return `<article class="metric"><div class="key">${escapeHtml(label)}</div><div class="val">${escapeHtml(fmt(value))}</div></article>`; }

export function renderHushMaskProfile() {
  const mask = selectedMask();
  const panel = $('hushMaskProfilePanel');
  if (!panel || !mask) return;
  const profile = buildHushMaskProfile(mask);
  const summary = profile.profileSummary || {};
  setHtml('hushMaskDescription', `<strong>${escapeHtml(mask.label || '')}</strong><br>${escapeHtml(mask.description || '')}<br><span>Use: ${escapeHtml(mask.intendedUse || '')}</span><br><span>Risk tell: ${escapeHtml(mask.riskTell || '')}</span>`);
  panel.innerHTML = [
    metricRow('Profile status', profile.profileStatus),
    metricRow('Words', summary.wordCount ?? 'unavailable'),
    metricRow('Avg sentence', summary.avgSentenceLength ?? 'unavailable'),
    metricRow('Punctuation', summary.punctuationDensity ?? 'unavailable'),
    metricRow('Contractions', summary.contractionDensity ?? 'unavailable'),
    metricRow('Recurrence', summary.recurrencePressure ?? 'unavailable'),
    metricRow('Warnings', asArray(profile.warnings).join(', ') || 'none')
  ].join('');
}

export function renderHushProfileMatch(match = benchState.hushProfileMatch) {
  const panel = $('hushProfileMatchPanel');
  if (!panel) return;
  if (!match) { panel.innerHTML = '<p class="section-note">Swap or analyze to calculate mask match.</p>'; return; }
  const summary = summarizeProfileMatch(match);
  panel.innerHTML = [
    '<div class="section-kicker">Mask Match</div>',
    metricRow('Match score', fmt(summary.matchScore)),
    metricRow('Tolerance', summary.toleranceStatus),
    metricRow('Semantic fidelity', fmt(summary.semanticFidelity)),
    metricRow('Source residual', fmt(summary.sourceResidualRisk)),
    metricRow('Protected literals', summary.protectedLiteralStatus || 'unavailable'),
    metricRow('Warnings', asArray(summary.warnings).join(', ') || 'none')
  ].join('');
}

function renderHushWarnings(result = benchState.hushSwapResult) {
  const warnings = result?.warnings || benchState.hushProfileMatch?.warnings || [];
  setHtml('hushSwapWarningsPanel', asArray(warnings).length ? asArray(warnings).map((item) => `<span class="chip">${escapeHtml(item)}</span>`).join(' ') : '<span class="section-note">No Hush swap warnings yet.</span>');
}

export function renderEscapeVector(vector = benchState.escapeVector) { const s = vector?.scores || {}; setHtml('escapeVectorGrid', [metricCard('Source Residual', s.sourceResidualRisk), metricCard('Mask Fit', s.maskFit), metricCard('Δsafe', s.maskDeltaSafe), metricCard('Semantic Fidelity', s.semanticFidelity), metricCard('Mask Linkability', s.maskLinkability), metricCard('Mask Drift', s.maskDrift), metricCard('Belonging Without Collapse', s.belongingWithoutCollapse), metricCard('Ingestion Friction', s.ingestionFriction), metricCard('Aperture Recapture', s.apertureRecaptureRisk)].join('')); }
export function renderRecognitionField(field = benchState.recognitionField) { const summary = field?.summary || {}; setHtml('recognitionFieldGrid', [metricCard('Recognition Pressure', summary.recognitionPressure), metricCard('Context Legibility', summary.contextLegibility), metricCard('Indexability', summary.indexability), metricCard('Topic Leakage', summary.topicLeakage), metricCard('Entity Leakage', summary.entityLeakage), metricCard('Persona Continuity', summary.personaContinuityPressure), metricCard('Mask Overuse', summary.maskOverusePressure), metricCard('Recapture Pressure', summary.recapturePressure)].join('')); const warnings = field ? [field.classifications?.route ? `route:${field.classifications.route}` : null, ...(field.warnings || []), ...(field.limitations || [])].filter(Boolean) : ['Run analysis to calculate context pressure.']; setHtml('recognitionFieldWarnings', warnings.map((item) => `<span class="chip">${escapeHtml(item)}</span>`).join(' ')); }
export function renderControllerDecision(decision = benchState.controllerDecision) { const label = STATE_LABELS[decision?.state] || 'Controller waiting'; setText('controllerStatePill', `Controller // ${label.toLowerCase()}`); setText('sealStatePill', decision?.state === 'seal' ? 'Seal // locally sealable' : 'Seal // unavailable'); const actions = (decision?.steeringActions || []).map((item) => `<li><strong>${escapeHtml(item.code)}</strong>: ${escapeHtml(item.rationale || '')}</li>`).join(''); const recognitionHints = (benchState.recognitionField?.recommendedControllerHints || []).map((item) => `<li><strong>${escapeHtml(item.code)}</strong>: ${escapeHtml(item.reason || '')}</li>`).join(''); const reasons = (decision?.reasons || []).map((item) => `<span class="chip">${escapeHtml(item)}</span>`).join(' '); const warnings = (decision?.warnings || []).map((item) => `<span class="chip">${escapeHtml(item)}</span>`).join(' '); setHtml('controllerPanel', `<div class="section-kicker">Controller / Steering Surface</div><h3 id="controllerHeading">${escapeHtml(label)}</h3><div id="controllerBody"><p><strong>Action:</strong> ${escapeHtml(decision?.action || 'waiting')}</p><p><strong>Confidence:</strong> ${escapeHtml(fmt(decision?.confidence))}</p><p><strong>Next instruction:</strong> ${escapeHtml(decision?.steeringPacket?.nextInstruction || 'Run analysis to surface steering instructions.')}</p><div><strong>Reasons:</strong> ${reasons || 'none'}</div><div><strong>Warnings:</strong> ${warnings || 'none'}</div><ul class="controller-action-list">${actions}</ul>${recognitionHints ? `<p><strong>Recognition Field hints:</strong></p><ul class="controller-action-list">${recognitionHints}</ul>` : ''}<p class="section-note">Locally sealable means bounded local convergence. It gives no identity verdict or platform guarantee.</p></div>`); }
export function renderPersonaMemory(memory = benchState.personaMemory) { if (!memory) { setText('personaMemoryBody', 'No local mask memory loaded. The selected mask is acting as a reference surface only.'); setText('maskMemorySummary', 'No local mask memory loaded.'); return; } const summary = summarizePersonaMemory(memory); const html = `<div>Mask Memory: <strong>${escapeHtml(summary.status)}</strong></div><div>Mask label: ${escapeHtml(summary.label)}</div><div>Accepted outputs: ${escapeHtml(summary.acceptedCount)}</div><div>Current entries: ${escapeHtml(summary.entryCount)}</div><div>Centroid features: ${escapeHtml(summary.field.centroidFeatureCount)}</div><div>Linkability: ${escapeHtml(summary.field.linkabilityStatus)}</div><div>Ingestion mean: ${escapeHtml(fmt(summary.field.meanIngestionFriction))}</div><div>Warnings: ${summary.warnings.length ? summary.warnings.map((w) => `<span class="chip">${escapeHtml(w)}</span>`).join(' ') : 'none'}</div>`; setHtml('personaMemoryBody', html); setHtml('maskMemorySummary', html); }
function ledgerRowToPreview(row) { return { t: row.t, source: row.scores.sourceResidualRisk, mask: row.scores.maskFit, delta: row.scores.maskDeltaSafe, semantic: row.scores.semanticFidelity, ingestion: row.scores.ingestionFriction, state: row.controller.state, action: row.controller.action }; }
function renderLedgerSummary() { const s = summarizeIterationLedger(benchState.iterationLedger); setHtml('ledgerSummaryBody', `<div>Ledger rows: ${escapeHtml(s.rowCount)}</div><div>Accepted rows: ${escapeHtml(s.acceptedCount)}</div><div>Latest state: ${escapeHtml(s.latestState)}</div><div>Latest output hash: ${escapeHtml(s.latestOutputHash || 'none')}</div><div>Latest accepted iteration ID: ${escapeHtml(s.latestAcceptedIterationId || 'none')}</div><div>Text export: ${escapeHtml(s.textExport)}</div>`); }
function renderIterationPreview() { const rowsSource = benchState.iterationLedger?.rows?.length ? benchState.iterationLedger.rows.map(ledgerRowToPreview) : benchState.iterationPreview; if (!rowsSource.length) { setHtml('iterationPreviewBody', '<p class="section-note">No iteration rows yet.</p>'); renderLedgerSummary(); return; } const rows = rowsSource.map((row) => `<tr><td>${row.t}</td><td>${fmt(row.source)}</td><td>${fmt(row.mask)}</td><td>${fmt(row.delta)}</td><td>${fmt(row.semantic)}</td><td>${fmt(row.ingestion)}</td><td>${escapeHtml(row.state)}</td><td>${escapeHtml(row.action)}</td></tr>`).join(''); setHtml('iterationPreviewBody', `<table class="iteration-preview-table"><thead><tr><th>t</th><th>Source</th><th>Mask</th><th>Δsafe</th><th>Semantic</th><th>Ingestion</th><th>State</th><th>Action</th></tr></thead><tbody>${rows}</tbody></table>`); renderLedgerSummary(); }
export function renderClaimCeiling(claim = benchState.claimCeiling) { if (!claim) { setHtml('claimCeilingPanel', '<p class="section-note">Run analysis to calculate claim ceiling.</p>'); return; } const reasons = (claim.reasons || []).map((item) => `<li>${escapeHtml(item)}</li>`).join(''); const limitations = (claim.limitations || []).slice(0, 5).map((item) => `<li>${escapeHtml(item)}</li>`).join(''); const warnings = (claim.warnings || []).map((item) => `<span class="chip">${escapeHtml(item)}</span>`).join(' '); setHtml('claimCeilingPanel', `<div><strong>Claim ceiling:</strong> ${escapeHtml(claim.label)}</div><div><strong>Permitted conclusion:</strong> ${escapeHtml(claim.allowedClaim)}</div><div><strong>Warnings:</strong> ${warnings || 'none'}</div><details><summary>Reasons and limitations</summary><ul>${reasons || '<li>No reasons recorded.</li>'}</ul><ul>${limitations || '<li>No limitations recorded.</li>'}</ul></details>`); }
function updateAcceptState() { const button = $('acceptOutputBtn'); const warning = $('acceptWarning'); if (!button) return; const state = benchState.controllerDecision?.state; const recognitionRoute = benchState.recognitionField?.classifications?.route; const recognitionHold = recognitionRoute === 'hold'; const allowed = Boolean(benchState.protectedOutputText.trim() && benchState.escapeVector && benchState.controllerDecision && ['seal', 'continue'].includes(state) && !recognitionHold); button.disabled = !allowed; if (warning) { warning.hidden = allowed || !state; warning.textContent = recognitionHold ? 'Accept is paused because Recognition Field route is hold. Review context pressure before accepting into Mask Memory.' : state && !allowed ? 'Accept is paused because the controller is asking for restore or hold. Edit the output or analyze again before accepting into Mask Memory.' : ''; } }
function appendLedgerRow(field) { const personaSummary = summarizePersonaMemory(benchState.personaMemory); benchState.iterationLedger = appendIterationRow(benchState.iterationLedger, { protectedBaselineText: benchState.protectedBaselineText, maskReferenceText: benchState.maskReferenceText, messageDraftText: benchState.messageDraftText, protectedOutputText: benchState.protectedOutputText, personaField: field, personaSummary, escapeVector: benchState.escapeVector, ingestionAudit: benchState.ingestionAudit, controllerDecision: benchState.controllerDecision, includeTexts: false }); const latestRow = benchState.iterationLedger.rows[benchState.iterationLedger.rows.length - 1]; if (latestRow?.id) benchState.iterationTextCache[latestRow.id] = { protectedBaseline: benchState.protectedBaselineText, maskReference: benchState.maskReferenceText, messageDraft: benchState.messageDraftText, protectedOutput: benchState.protectedOutputText }; benchState.iterationPreview = benchState.iterationLedger.rows.map(ledgerRowToPreview); renderIterationPreview(); }
function buildRecognitionLayer() { const personaSummary = summarizePersonaMemory(benchState.personaMemory); benchState.contextProfile = buildContextProfile({ contextType: benchState.recognitionContextType, intendedMode: benchState.recognitionIntentMode, exposureDuration: benchState.recognitionExposureDuration, protectedBaselineText: benchState.protectedBaselineText, maskReferenceText: benchState.maskReferenceText, messageDraftText: benchState.messageDraftText, protectedOutputText: benchState.protectedOutputText, protectedLiterals: extractProtectedLiterals(), escapeVector: benchState.escapeVector, ingestionAudit: benchState.ingestionAudit, personaSummary, iterationLedger: benchState.iterationLedger }); benchState.recognitionField = buildRecognitionField({ protectedBaselineText: benchState.protectedBaselineText, maskReferenceText: benchState.maskReferenceText, messageDraftText: benchState.messageDraftText, protectedOutputText: benchState.protectedOutputText, protectedLiterals: extractProtectedLiterals(), escapeVector: benchState.escapeVector, ingestionAudit: benchState.ingestionAudit, controllerDecision: benchState.controllerDecision, personaSummary, iterationLedger: benchState.iterationLedger, claimCeiling: benchState.claimCeiling, contextProfile: benchState.contextProfile, options: { contextType: benchState.recognitionContextType, intendedMode: benchState.recognitionIntentMode, exposureDuration: benchState.recognitionExposureDuration } }); renderRecognitionField(); return benchState.recognitionField; }
function evaluateAndRenderClaimCeiling() { benchState.claimCeiling = evaluateClaimCeiling({ escapeVector: benchState.escapeVector, ingestionAudit: benchState.ingestionAudit, controllerDecision: benchState.controllerDecision, personaSummary: summarizePersonaMemory(benchState.personaMemory), iterationLedger: benchState.iterationLedger, reportIntent: 'local-review' }); renderClaimCeiling(); return benchState.claimCeiling; }
export function buildCurrentReportPayload() { if (!benchState.claimCeiling) evaluateAndRenderClaimCeiling(); if (!benchState.recognitionField && benchState.escapeVector) buildRecognitionLayer(); benchState.reportPayload = buildReportPayload({ escapeVector: benchState.escapeVector, ingestionAudit: benchState.ingestionAudit, controllerDecision: benchState.controllerDecision, personaSummary: summarizePersonaMemory(benchState.personaMemory), iterationLedger: benchState.iterationLedger, claimCeiling: benchState.claimCeiling, recognitionField: benchState.recognitionField, protectedLiterals: extractProtectedLiterals(), options: { includeTexts: false, includeLedger: true, includePrivateText: false } }); return benchState.reportPayload; }
export function exportCurrentReportJson() { const payload = buildCurrentReportPayload(); const json = exportReportJson(payload, { pretty: true }); const output = $('reportExportOutput'); if (output) output.value = json; return json; }
export function exportCurrentReportMarkdown() { const payload = buildCurrentReportPayload(); const markdown = exportReportMarkdown(payload); const output = $('reportExportOutput'); if (output) output.value = markdown; return markdown; }
export function analyzeProtectedOutput() { readInputs(); extractProfiles(); ensurePersonaMemory(); const field = activePersonaField(); const protectedLiterals = extractProtectedLiterals(); benchState.ingestionAudit = buildIngestionFrictionAudit({ text: benchState.protectedOutputText, protectedLiterals, canonicalTokens: CANONICAL_TOKENS }); benchState.escapeVector = buildEscapeVector({ protectedBaselineText: benchState.protectedBaselineText, maskText: benchState.maskReferenceText || selectedMask()?.sampleSeed || selectedMask()?.description || '', maskProfile: field.maskProfile || benchState.profiles.maskReference, maskHistory: field.maskHistory || [], draftText: benchState.messageDraftText, outputText: benchState.protectedOutputText, outputProfile: benchState.profiles.protectedOutput, protectedLiterals, ingestionAudit: benchState.ingestionAudit, options: { mode: DEFAULT_MODE, targetContext: 'TD613 Hush', canonicalTokens: CANONICAL_TOKENS, thresholds: { minWords: 5 } } }); benchState.controllerDecision = buildEscapeControllerDecision({ vector: benchState.escapeVector, mode: DEFAULT_MODE, operatorIntent: { priority: 'source-reduction', targetContext: 'TD613 Hush' } }); renderProfiles(); renderEscapeVector(); renderPersonaMemory(); appendLedgerRow(field); evaluateAndRenderClaimCeiling(); buildRecognitionLayer(); benchState.hushProfileMatch = buildProfileMatch({ sourceText: benchState.messageDraftText, outputText: benchState.protectedOutputText, maskProfile: field.maskProfile || benchState.profiles.maskReference, protectedLiterals, escapeVector: benchState.escapeVector, ingestionAudit: benchState.ingestionAudit, recognitionField: benchState.recognitionField }); renderHushProfileMatch(); renderHushWarnings(); renderControllerDecision(); updateAcceptState(); return { vector: benchState.escapeVector, decision: benchState.controllerDecision, ledger: benchState.iterationLedger, claimCeiling: benchState.claimCeiling, recognitionField: benchState.recognitionField, profileMatch: benchState.hushProfileMatch }; }
export function runHushSwap() { readInputs(); extractProfiles(); ensurePersonaMemory(); const mask = selectedMask(); const field = activePersonaField(); const protectedLiterals = extractProtectedLiterals(); const result = buildHushSwap({ sourceText: benchState.messageDraftText, protectedBaselineText: benchState.protectedBaselineText, mask, maskProfile: field.maskProfile || mask?.profile || benchState.profiles.maskReference, maskReferenceText: benchState.maskReferenceText || mask?.sampleSeed || '', protectedLiterals, operatorMode: benchState.recognitionIntentMode, contextType: benchState.recognitionContextType, exposureDuration: benchState.recognitionExposureDuration, personaSummary: summarizePersonaMemory(benchState.personaMemory), iterationLedger: benchState.iterationLedger, options: { candidateCount: 5, includePrivateText: false } }); benchState.hushSwapResult = result; benchState.hushProfileMatch = result.match; const output = $('protectedOutputInput'); if (output) output.value = result.selectedOutput || ''; benchState.protectedOutputText = result.selectedOutput || ''; renderHushProfileMatch(); renderHushWarnings(result); if (benchState.protectedOutputText.trim()) analyzeProtectedOutput(); return result; }
export function generateMaskedOutput() { return runHushSwap().selectedOutput || ''; }
export function acceptOutputIntoPersonaMemory() { readInputs(); if (!benchState.protectedOutputText.trim()) return null; if (!benchState.escapeVector || !benchState.controllerDecision) analyzeProtectedOutput(); if (!['seal', 'continue'].includes(benchState.controllerDecision?.state) || benchState.recognitionField?.classifications?.route === 'hold') { updateAcceptState(); return null; } benchState.personaMemory = appendAcceptedOutput(ensurePersonaMemory(), { text: benchState.protectedOutputText, profile: benchState.profiles.protectedOutput, escapeVector: benchState.escapeVector, ingestionAudit: benchState.ingestionAudit, controllerDecision: benchState.controllerDecision, acceptance: { acceptedBy: 'operator', reason: benchState.controllerDecision.state, stateAtAcceptance: benchState.controllerDecision.state } }); const latestEntry = benchState.personaMemory.memory.entries[benchState.personaMemory.memory.entries.length - 1]; const latestRow = benchState.iterationLedger.rows[benchState.iterationLedger.rows.length - 1]; if (latestRow) benchState.iterationLedger = linkAcceptedOutputToIteration(benchState.iterationLedger, { iterationId: latestRow.id, personaMemoryEntryId: latestEntry?.id || null }); benchState.iterationPreview = benchState.iterationLedger.rows.map(ledgerRowToPreview); renderPersonaMemory(); renderIterationPreview(); evaluateAndRenderClaimCeiling(); buildRecognitionLayer(); renderControllerDecision(); updateAcceptState(); return benchState.personaMemory; }
function ledgerForExplicitTextExport() { return { ...benchState.iterationLedger, rows: benchState.iterationLedger.rows.map((row) => { const cached = benchState.iterationTextCache[row.id]; if (!cached) return row; return { ...row, texts: { protectedBaseline: cached.protectedBaseline, maskReference: cached.maskReference, messageDraft: cached.messageDraft, protectedOutput: cached.protectedOutput }, textIncluded: { protectedBaseline: true, maskReference: true, messageDraft: true, protectedOutput: true } }; }) }; }
export function exportLedgerJson() { const includeTexts = Boolean($('includeLedgerTextsToggle')?.checked); const ledger = includeTexts ? ledgerForExplicitTextExport() : benchState.iterationLedger; const json = exportIterationLedgerJson(ledger, { includeTexts, pretty: true }); const output = $('ledgerExportOutput'); if (output) output.value = json; renderLedgerSummary(); return json; }
export function exportCurrentHushMaskProfile() { const mask = selectedMask(); const json = mask?.source === 'custom' ? exportCustomMaskJson(mask, { includePrivateText: false }) : exportHushMaskJson(mask, { includePrivateText: false }); const output = $('ledgerExportOutput'); if (output) output.value = json; return json; }
export function exportCurrentHushSwapJson() { const json = exportHushSwapJson(benchState.hushSwapResult || {}, { includePrivateText: false }); const output = $('ledgerExportOutput'); if (output) output.value = json; return json; }
export function resetBench() { for (const id of ['protectedBaselineInput', 'maskReferenceInput', 'messageDraftInput', 'protectedOutputInput']) { const el = $(id); if (el) el.value = ''; } benchState.protectedBaselineText = ''; benchState.maskReferenceText = ''; benchState.messageDraftText = ''; benchState.protectedOutputText = ''; benchState.profiles = initialProfiles(); benchState.ingestionAudit = null; benchState.escapeVector = null; benchState.controllerDecision = null; benchState.claimCeiling = null; benchState.contextProfile = null; benchState.recognitionField = null; benchState.reportPayload = null; benchState.hushProfileMatch = null; benchState.hushSwapResult = null; benchState.iterationPreview = []; benchState.iterationTextCache = {}; benchState.iterationLedger = createIterationLedger({ context: { benchVersion: 'phase-11', product: 'TD613 Hush', mode: DEFAULT_MODE, selectedMaskId: benchState.selectedHushMaskId, selectedMaskLabel: selectedMask()?.label || '', recognitionContextType: benchState.recognitionContextType, recognitionIntentMode: benchState.recognitionIntentMode, recognitionExposureDuration: benchState.recognitionExposureDuration } }); renderProfiles(); renderEscapeVector({ scores: {} }); renderRecognitionField(null); renderControllerDecision(null); renderPersonaMemory(benchState.personaMemory); renderIterationPreview(); renderClaimCeiling(null); renderHushProfileMatch(null); renderHushWarnings(null); const ledgerOutput = $('ledgerExportOutput'); if (ledgerOutput) ledgerOutput.value = ''; const reportOutput = $('reportExportOutput'); if (reportOutput) reportOutput.value = ''; updateAcceptState(); }
export function renderHushMaskOptions() { const select = $('maskFieldSelect'); if (!select) return; const masks = [...benchState.hushMasks, ...benchState.customMasks]; const liveSelected = select.value || benchState.selectedHushMaskId; select.innerHTML = masks.map((mask) => `<option value="${escapeHtml(mask.id)}">${escapeHtml(mask.label)} — ${escapeHtml(mask.family || mask.profileStatus || 'Hush mask')}</option>`).join(''); if (liveSelected && masks.some((mask) => mask.id === liveSelected)) benchState.selectedHushMaskId = liveSelected; if (!benchState.selectedHushMaskId && select.options.length) benchState.selectedHushMaskId = select.options[0].value; select.value = benchState.selectedHushMaskId; }
export function selectHushMask(maskId = '') { const masks = [...benchState.hushMasks, ...benchState.customMasks]; const mask = masks.find((item) => item.id === maskId) || masks[0] || null; benchState.selectedHushMaskId = mask?.id || ''; benchState.selectedPersonaId = benchState.selectedHushMaskId; benchState.selectedHushMask = mask; const reference = $('maskReferenceInput'); if (reference && mask) reference.value = mask.sampleSeed || mask.samples?.map((sample) => sample.text).filter(Boolean).join('\n\n') || mask.description || ''; readInputs(); extractProfiles(); benchState.personaMemory = createMemoryForMask(mask); benchState.iterationLedger = createIterationLedger({ context: { benchVersion: 'phase-11', product: 'TD613 Hush', mode: DEFAULT_MODE, selectedMaskId: benchState.selectedHushMaskId, selectedMaskLabel: selectedMask()?.label || '', recognitionContextType: benchState.recognitionContextType, recognitionIntentMode: benchState.recognitionIntentMode, recognitionExposureDuration: benchState.recognitionExposureDuration } }); benchState.iterationTextCache = {}; benchState.claimCeiling = null; benchState.contextProfile = null; benchState.recognitionField = null; benchState.reportPayload = null; renderPersonaMemory(); renderProfiles(); renderIterationPreview(); renderRecognitionField(null); renderClaimCeiling(null); return mask; }
function populatePersonas() { benchState.hushMasks = listHushMasks(); renderHushMaskOptions(); if (!benchState.selectedHushMaskId && benchState.hushMasks.length) benchState.selectedHushMaskId = benchState.hushMasks[0].id; selectHushMask(benchState.selectedHushMaskId); }
function populateRecognitionContexts() { const select = $('recognitionContextType'); if (!select) return; select.innerHTML = CONTEXT_TYPES.map((context) => `<option value="${escapeHtml(context.id)}">${escapeHtml(context.label)}</option>`).join(''); select.value = benchState.recognitionContextType; const mode = $('recognitionIntentMode'); if (mode) mode.value = benchState.recognitionIntentMode; const duration = $('recognitionExposureDuration'); if (duration) duration.value = benchState.recognitionExposureDuration; }
function updateRecognitionOptions() { readInputs(); if (benchState.escapeVector) { buildRecognitionLayer(); renderControllerDecision(); updateAcceptState(); } }
export function switchHushMaskTab(tab = 'built-in') { benchState.hushMode = tab === 'customize' ? 'customize' : 'built-in'; const builtIn = $('hushBuiltInMaskPanel'); const custom = $('hushCustomizePanel'); const builtBtn = $('hushBuiltInTabBtn'); const customBtn = $('hushCustomizeTabBtn'); if (builtIn) builtIn.hidden = benchState.hushMode !== 'built-in'; if (custom) custom.hidden = benchState.hushMode !== 'customize'; builtBtn?.setAttribute('aria-pressed', benchState.hushMode === 'built-in' ? 'true' : 'false'); customBtn?.setAttribute('aria-pressed', benchState.hushMode === 'customize' ? 'true' : 'false'); }
export function addHushCustomMaskSample() { const name = $('hushCustomMaskName')?.value || 'Custom Mask'; const sample = $('hushCustomMaskSampleInput')?.value || ''; if (!benchState.activeCustomMask || benchState.activeCustomMask.label !== name) benchState.activeCustomMask = createCustomMask({ label: name }); benchState.activeCustomMask = addCustomMaskSample(benchState.activeCustomMask, sample, { includePrivateText: true }); renderHushCustomMaskSummary(); return benchState.activeCustomMask; }
function renderHushCustomMaskSummary() { const summary = benchState.activeCustomMask ? summarizeCustomMask(benchState.activeCustomMask) : null; if (!summary) { setText('hushCustomMaskSummary', 'No custom mask samples yet.'); return; } setHtml('hushCustomMaskSummary', [metricRow('Samples', summary.sampleCount), metricRow('Total words', summary.totalWords), metricRow('Profile status', summary.profileStatus), metricRow('Warnings', summary.warnings.join(', ') || 'none')].join('')); }
export function saveHushCustomMask() { if (!benchState.activeCustomMask) return null; const saved = rebuildCustomMaskProfile(benchState.activeCustomMask, { includePrivateText: true }); saved.family = 'custom Hush mask'; saved.description = `Custom mask built from ${saved.sampleCount} local sample(s).`; saved.intendedUse = 'Operator-defined local mask surface.'; saved.riskTell = 'Custom samples can overfit if the sample set is narrow.'; saved.sampleSeed = saved.samples.map((sample) => sample.text).filter(Boolean).join('\n\n'); saved.profile = saved.compositeProfile; benchState.customMasks = [...benchState.customMasks.filter((mask) => mask.id !== saved.id), saved]; renderHushMaskOptions(); selectHushMask(saved.id); switchHushMaskTab('built-in'); return saved; }
export function initHushMaskStudio(root = documentRef) { docRef = root || docRef; populatePersonas(); renderHushCustomMaskSummary(); renderHushMaskProfile(); $('hushBuiltInTabBtn')?.addEventListener('click', () => switchHushMaskTab('built-in')); $('hushCustomizeTabBtn')?.addEventListener('click', () => switchHushMaskTab('customize')); $('hushAddSampleBtn')?.addEventListener('click', addHushCustomMaskSample); $('hushSaveCustomMaskBtn')?.addEventListener('click', saveHushCustomMask); $('exportHushMaskProfileBtn')?.addEventListener('click', exportCurrentHushMaskProfile); $('exportHushSwapJsonBtn')?.addEventListener('click', exportCurrentHushSwapJson); }
export function initAdversarialBench(documentRef = document) { docRef = documentRef; if (!docRef || initializedFor === documentRef) return benchState; initializedFor = documentRef; populateRecognitionContexts(); initHushMaskStudio(documentRef); ensurePersonaMemory(); benchState.iterationLedger = createIterationLedger({ context: { benchVersion: 'phase-11', product: 'TD613 Hush', mode: DEFAULT_MODE, selectedMaskId: benchState.selectedHushMaskId, selectedMaskLabel: selectedMask()?.label || '', recognitionContextType: benchState.recognitionContextType, recognitionIntentMode: benchState.recognitionIntentMode, recognitionExposureDuration: benchState.recognitionExposureDuration } }); benchState.iterationTextCache = {}; renderProfiles(); renderEscapeVector({ scores: {} }); renderRecognitionField(null); renderControllerDecision(null); renderPersonaMemory(); renderIterationPreview(); renderClaimCeiling(null); renderHushProfileMatch(null); renderHushWarnings(null); updateAcceptState(); $('generateMaskedOutputBtn')?.addEventListener('click', generateMaskedOutput); $('analyzeOutputBtn')?.addEventListener('click', analyzeProtectedOutput); $('acceptOutputBtn')?.addEventListener('click', acceptOutputIntoPersonaMemory); $('resetBenchBtn')?.addEventListener('click', resetBench); $('exportLedgerJsonBtn')?.addEventListener('click', exportLedgerJson); $('exportReportJsonBtn')?.addEventListener('click', exportCurrentReportJson); $('exportReportMarkdownBtn')?.addEventListener('click', exportCurrentReportMarkdown); for (const id of ['recognitionContextType', 'recognitionIntentMode', 'recognitionExposureDuration']) $(id)?.addEventListener('change', updateRecognitionOptions); $('maskFieldSelect')?.addEventListener('change', () => selectHushMask($('maskFieldSelect')?.value || '')); for (const id of ['protectedBaselineInput', 'maskReferenceInput', 'messageDraftInput', 'protectedOutputInput']) $(id)?.addEventListener('input', () => { readInputs(); extractProfiles(); renderProfiles(); }); return benchState; }
export const ready = typeof document !== 'undefined' && document.body?.dataset?.pageKind === 'adversarial-bench' ? initAdversarialBench(document) : benchState;
