import assert from 'node:assert/strict';
import fs from 'node:fs';
const read = p => fs.readFileSync(new URL(`../../${p}`, import.meta.url), 'utf8');
const ledger = read('docs/ASH_KEEP_BUILDOUT_LEDGER.md');
const roadmap = read('ROADMAP.md');
const closure = read('docs/APERTURE_COMPOSITION_CLOSURE_RECEIPT.md');
const stretch6 = read('docs/ASH_KEEP_STRETCH6_CLOSURE_RECEIPT.md');
const stretch7 = read('docs/ASH_KEEP_STRETCH7_CLOSURE_RECEIPT.md');
const stretch8 = read('docs/ASH_KEEP_STRETCH8_CLOSURE_RECEIPT.md');
const stretch9 = read('docs/ASH_KEEP_STRETCH9_CLOSURE_RECEIPT.md');
const stretch10 = read('docs/ASH_KEEP_STRETCH10_CLOSURE_RECEIPT.md');
const stretch11 = read('docs/ASH_KEEP_STRETCH11_CLOSURE_RECEIPT.md');
const buildout = read('docs/ASH_KEEP_BUILDOUT_CLOSURE_RECEIPT.md');
const law = read('docs/STRATEGIC_VERCEL_DEPLOYMENT_LAW.md');
assert.match(ledger, /Ledger generation: `v2\.0/);
assert.match(ledger, /component maturity after Stretch 11 local closure = 358 \/ 375/);
assert.match(ledger, /remaining component maturity = 17 \/ 375/);
assert.match(ledger, /production-demonstrated workstreams after exact-main seal = 5 \/ 9/);
assert.match(ledger, /transport-capable workstreams = 1 \/ 9/);
assert.match(ledger, /Stretch 10 — CLOSED AND STRATEGICALLY SEALED/);
assert.match(ledger, /Stretch 11 — CLOSED LOCALLY/);
assert.match(roadmap, /Roadmap generation: `v2\.0/);
assert.match(roadmap, /Aperture composition = 18 \/ 25/);
assert.match(roadmap, /Stretch 1 — CLOSED/);
assert.match(roadmap, /Stretch 11 · Destination-Bound Handoff — CLOSED LOCALLY/);
assert.match(roadmap, /Ash Keep Buildout Closure — NOT A STRETCH/);
assert.match(closure, /status: CLOSED/);
assert.match(closure, /maturity: IMPLEMENTED_VALIDATION_GATED/);
for (const receipt of [stretch6,stretch7,stretch8,stretch9,stretch10]) assert.match(receipt, /State: `CLOSED \/ IMPLEMENTED_VALIDATION_GATED \/ EVIDENCE_BOUNDED`/);
assert.match(stretch11, /State: `CLOSED \/ IMPLEMENTED_VALIDATION_GATED \/ EVIDENCE_BOUNDED \/ PENDING_EXACT_MAIN_EXTERNAL_SEAL`/);
assert.match(buildout, /FURTHER_STRETCH_NUMBERING_FORBIDDEN/);
assert.match(law, /branch work ≠ deployment requirement/);
assert.match(law, /Exceptions must be recorded/);
console.log('stretch1-preservation/packet-state.test.mjs passed');
