import pathlib,json,hashlib,subprocess,datetime
ROOT=pathlib.Path('/workspace/scratch/26d2ceda3f9e'); RUN=ROOT/'continuation-a17'; PRIOR=ROOT/'continuation-a16'; CALLER=ROOT/'caller-a17'
def read(p): return json.loads(p.read_bytes())
def h(b): return hashlib.sha256(b).hexdigest()
def canon(v): return json.dumps(v,sort_keys=True,separators=(',',':'),ensure_ascii=False).encode()
def write(p,v):
 with p.open('x') as f: json.dump(v,f,ensure_ascii=False,indent=2); f.write('\n')
release=read(RUN/'credential.body.bin')['source_commit']; source=read(RUN/'source.body.bin')['source_packet_commit']; fingerprint='51efc3d87cdffc4fb2869519ff4fa12b10ce179ba79d3976f6094cf741681c39'
ledger=read(RUN/'LIVE_LEDGER_PRE_FREEZE.json'); runs=ledger['runs']; totals={'reserved_calls':sum(x['calls_reserved'] for x in runs),'reserved_cost_nanos':sum(x['reserved_cost_nanos'] for x in runs),'active_runs':sum(x['status']=='ACTIVE' for x in runs)}
assert totals=={'reserved_calls':76,'reserved_cost_nanos':8698567500,'active_runs':0}
assert not any(x['run_id'].endswith('-a17') for x in runs)
assert read(RUN/'credential.body.bin')['credential_sha256']==fingerprint
for a,count,cost in [('a12',0,0),('a13',5,551226000),('a14',1,110168250),('a15',9,996168000),('a16',1,110195250)]:
 r=next(x for x in runs if x['run_id'].endswith('-'+a)); assert r['status']=='HELD' and r['calls_reserved']==count and r['reserved_cost_nanos']==cost
assert read(RUN/'OPERATOR_PAID_BINDING.json')['attestation_accepted_for_prospective_billing_gate']
subprocess.run(['git','clone','--no-hardlinks',str(ROOT/'caller-a16'),str(CALLER)],check=True,capture_output=True)
for target in ['server/loom-assay-contract.js','server/loom-assay-run-config.json']: (CALLER/target).write_bytes((ROOT/'a17-repair'/target).read_bytes())
token=pathlib.Path('/workspace/scratch/9d69e9b2a01d/recovery-private/assay-relay-access.token').read_bytes().strip(); config=read(CALLER/'server/loom-assay-run-config.json'); assert h(token)==config['access_sha256'] and 'portable-loom-first-receiver-20261009-a17' in config['run_ids']
lock=read(CALLER/'RESTORED_SOURCE_LOCK.json'); lock.update(original_deployed_commit=release,source_packet_commit=source,adaptation='Fresh three-call a17 caller; original prompt and provider wire bytes, decoding, credential/source checks and same-run predecessors retained.')
for f in lock['files']: f['local_sha256']=h((CALLER/f['path']).read_bytes())
(CALLER/'RESTORED_SOURCE_LOCK.json').write_text(json.dumps(lock,indent=2)+'\n')
subprocess.run(['git','add','RESTORED_SOURCE_LOCK.json','server/loom-assay-contract.js','server/loom-assay-run-config.json'],cwd=CALLER,check=True)
subprocess.run(['git','-c','user.name=Amari','-c','user.email=amari@td613.local','commit','-m','Freeze fresh three-call a17 caller'],cwd=CALLER,check=True,capture_output=True)
commit=subprocess.check_output(['git','rev-parse','HEAD'],cwd=CALLER,text=True).strip(); assert subprocess.check_output(['git','status','--porcelain'],cwd=CALLER,text=True).strip()==''
runner=(PRIOR/'run-targeted-a16.mjs').read_text().replace('continuation-a16','continuation-a17').replace('caller-a16','caller-a17').replace('A16','A17').replace('run-targeted-a16.mjs','run-targeted-a17.mjs').replace('plan.calls.length === 5','plan.calls.length === 3').replace('policy.binding.limits.max_calls === 5','policy.binding.limits.max_calls === 3'); (RUN/'run-targeted-a17.mjs').write_text(runner)
now=datetime.datetime.now(datetime.timezone.utc); at=now.isoformat(); runid='portable-loom-first-receiver-20261009-a17'
scope='Fresh three-call R06-2 acquisition, turns 0,1,2, in preserved a16 order. Turn 0 separately replaces the a16 HOLD and provides same-run setup; turn 1 separately replaces the a15 HOLD; turn 2 remains unattempted. R09-1 remains pending. Shared 80-call/$10 caps retained; local maximum USD 0.54216. Same model/configuration, zero automatic retries, stop globally at first HOLD, raw custody only.'
write(RUN/'AUTHORIZATION.json',{'schema':'td613.loom.receiver-repair-authorization/v0.1','run_id':runid,'recorded_at':at,'user_gesture':'why can’t you just do it and take my word for it that it’s correct ⟐','standing_acquisition_gesture':'do you need to go ahead and get the remaining left that isn’t ? if so, do it now 𝌋','scope':scope,'billing_status':'OPERATOR_ATTESTED_PAID','billing_gate_disposition':'OPERATOR_CONFIRMATION_ACCEPTED_AFTER_SCREENSHOT','prior_run':'portable-loom-first-receiver-20261009-a16','prior_run_preserved':True,'automatic_retries':0,'provider_calls_before_freeze':0,'governed_source_change_pr':1446})
policy=read(PRIOR/'POLICY.json'); policy.update(run_id=runid,protocol_commit=release,expires_at=(now+datetime.timedelta(hours=3)).isoformat()); policy['binding']['protocol_commit']=release; policy['binding']['limits'].update(max_calls=3,max_cost_usd=.54216); policy['binding']['authorization']={'record':str(RUN/'AUTHORIZATION.json'),'scope':scope+' Expected provider SHA-256 '+fingerprint+'; paid association OPERATOR_ATTESTED_PAID.'}; policy['program']['run_ids'].append(runid); write(RUN/'POLICY.json',policy)
plan=read(PRIOR/'PLAN.json'); plan.update(run_id=runid,protocol_commit=release,source_packet_commit=source,local_caller_commit=commit,maximum_calls=3,maximum_reserved_cost_nanos=542160000,runner_sha256=h((RUN/'run-targeted-a17.mjs').read_bytes())); plan['trial_order']=plan['trial_order'][:1]; plan['calls']=plan['calls'][:3]; plan['transport_environment']['working_directory']=str(CALLER); plan['continuation']={'prior_plan_canonical_sha256':h(canon(read(PRIOR/'PLAN.json'))),'prior_run':'portable-loom-first-receiver-20261009-a16','prior_call_numbers':[1,2,3],'call_1_class':'SEPARATELY_AUTHORIZED_REPLACEMENT_OF_A16_HOLD_AND_FRESH_SAME_RUN_SETUP','call_2_class':'SEPARATELY_AUTHORIZED_REPLACEMENT_OF_A15_HOLD','call_3_class':'ORIGINALLY_UNATTEMPTED','same_run_predecessors_required':True,'prior_answer_bytes_imported':False,'pending_other_trial':read(PRIOR/'PLAN.json')['calls'][3:]}; write(RUN/'PLAN.json',plan)
binding=read(PRIOR/'RECONSTRUCTED_CALLER_BINDING.json'); binding.update(deployed_commit=release,source_packet_commit=source,local_git_commit=commit,source_lock_sha256=h((CALLER/'RESTORED_SOURCE_LOCK.json').read_bytes()),adaptation=lock['adaptation']); write(RUN/'RECONSTRUCTED_CALLER_BINDING.json',binding)
write(RUN/'CREDENTIAL_BINDING.json',{'expected_provider_credential_sha256':fingerprint,'relay_access_sha256':h(token),'observation_receipt':'credential.receipt.json','production_source':release,'billing_status':'OPERATOR_ATTESTED_PAID','google_project_id':'gen-lang-client-0182177437','billing_evidence_ref':'OPERATOR_PAID_BINDING.json','authorization_ref':'AUTHORIZATION.json','source_header_required':True,'credential_header_required':True,'zero_generation_probes':True})
write(RUN/'SOURCE_VERIFICATION.json',{'checked_at':at,'source_packet_commit':source,'release_commit':release,'artifact_sha256':policy['artifact_sha256'],'caller_commit':commit,'source_lock_sha256':binding['source_lock_sha256'],'github_locked_source_bytes_match':True,'prior_a16_order_retained':plan['calls']==read(PRIOR/'PLAN.json')['calls'][:3],'provider_calls':0})
(RUN/'raw').mkdir()
print(json.dumps({'status':'A17_PREPARED_NOT_ENROLLED','caller_commit':commit,'billing':'OPERATOR_ATTESTED_PAID','policy_expires_at':policy['expires_at'],'planned_calls':len(plan['calls'])}))
